// Code generated by Kitex v0.15.4. DO NOT EDIT.

package core_api

import (
	"github.com/xh-polaris/psych-idl/kitex_gen/basic"
	"github.com/xh-polaris/psych-idl/kitex_gen/profile"

	"github.com/cloudwego/prutal"
)

type UserSignInReq struct {
	UnitId     string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	AuthType   int32  `protobuf:"varint,2,opt,name=authType" json:"authType,omitempty"`
	AuthId     string `protobuf:"bytes,3,opt,name=authId" json:"authId,omitempty"`
	VerifyCode string `protobuf:"bytes,4,opt,name=verifyCode" json:"verifyCode,omitempty"`
}

func (x *UserSignInReq) Reset() { *x = UserSignInReq{} }

func (x *UserSignInReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserSignInReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserSignInReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UserSignInReq) GetAuthType() int32 {
	if x != nil {
		return x.AuthType
	}
	return 0
}

func (x *UserSignInReq) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *UserSignInReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type UserSignInResp struct {
	UnitId    string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	CodeType  string `protobuf:"bytes,3,opt,name=codeType" json:"codeType,omitempty"`
	CodeValue string `protobuf:"bytes,4,opt,name=codeValue" json:"codeValue,omitempty"`
	Token     string `protobuf:"bytes,5,opt,name=token" json:"token,omitempty"`
	Code      int32  `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg       string `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UserSignInResp) Reset() { *x = UserSignInResp{} }

func (x *UserSignInResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserSignInResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserSignInResp) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UserSignInResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSignInResp) GetCodeType() string {
	if x != nil {
		return x.CodeType
	}
	return ""
}

func (x *UserSignInResp) GetCodeValue() string {
	if x != nil {
		return x.CodeValue
	}
	return ""
}

func (x *UserSignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserSignInResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserSignInResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取信息
type UserGetInfoReq struct {
}

func (x *UserGetInfoReq) Reset() { *x = UserGetInfoReq{} }

func (x *UserGetInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserGetInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type UserGetInfoResp struct {
	User *profile.User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Code int32         `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg  string        `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UserGetInfoResp) Reset() { *x = UserGetInfoResp{} }

func (x *UserGetInfoResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserGetInfoResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserGetInfoResp) GetUser() *profile.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserGetInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserGetInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 数据看板
type DashboardGetDataOverviewReq struct {
	UnitId *string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
}

func (x *DashboardGetDataOverviewReq) Reset() { *x = DashboardGetDataOverviewReq{} }

func (x *DashboardGetDataOverviewReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardGetDataOverviewReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardGetDataOverviewReq) GetUnitId() string {
	if x != nil && x.UnitId != nil {
		return *x.UnitId
	}
	return ""
}

type DashboardGetDataOverviewResp struct {
	TotalUsers                                   int32    `protobuf:"varint,1,opt,name=totalUsers" json:"totalUsers,omitempty"`
	WeeklyIncreaseUsers                          int32    `protobuf:"varint,2,opt,name=weeklyIncreaseUsers" json:"weeklyIncreaseUsers,omitempty"`
	WeeklyIncreaseUsersRate                      float64  `protobuf:"fixed64,3,opt,name=weeklyIncreaseUsersRate" json:"weeklyIncreaseUsersRate,omitempty"`
	ActiveUsers                                  *int32   `protobuf:"varint,4,opt,name=activeUsers" json:"activeUsers,omitempty"`
	WeeklyIncreaseActiveUsers                    *int32   `protobuf:"varint,5,opt,name=weeklyIncreaseActiveUsers" json:"weeklyIncreaseActiveUsers,omitempty"`
	WeeklyIncreaseActiveUsersRate                *float64 `protobuf:"fixed64,6,opt,name=weeklyIncreaseActiveUsersRate" json:"weeklyIncreaseActiveUsersRate,omitempty"`
	TotalConversations                           int32    `protobuf:"varint,7,opt,name=totalConversations" json:"totalConversations,omitempty"`
	WeeklyIncreaseConversations                  int32    `protobuf:"varint,8,opt,name=weeklyIncreaseConversations" json:"weeklyIncreaseConversations,omitempty"`
	WeeklyIncreaseConversationsRate              float64  `protobuf:"fixed64,9,opt,name=weeklyIncreaseConversationsRate" json:"weeklyIncreaseConversationsRate,omitempty"`
	AverageTimePerConversation                   float64  `protobuf:"fixed64,10,opt,name=averageTimePerConversation" json:"averageTimePerConversation,omitempty"`                             // minutes
	WeeklyIncreaseAverageTimePerConversation     float64  `protobuf:"fixed64,11,opt,name=weeklyIncreaseAverageTimePerConversation" json:"weeklyIncreaseAverageTimePerConversation,omitempty"` // minutes
	WeeklyIncreaseAverageTimePerConversationRate float64  `protobuf:"fixed64,12,opt,name=weeklyIncreaseAverageTimePerConversationRate" json:"weeklyIncreaseAverageTimePerConversationRate,omitempty"`
	AlarmUsers                                   int32    `protobuf:"varint,13,opt,name=alarmUsers" json:"alarmUsers,omitempty"`
	WeeklyIncreaseAlarmUsers                     int32    `protobuf:"varint,14,opt,name=weeklyIncreaseAlarmUsers" json:"weeklyIncreaseAlarmUsers,omitempty"`
	WeeklyIncreaseAlarmUsersRate                 float64  `protobuf:"fixed64,15,opt,name=weeklyIncreaseAlarmUsersRate" json:"weeklyIncreaseAlarmUsersRate,omitempty"`
	TotalUnits                                   *int32   `protobuf:"varint,16,opt,name=totalUnits" json:"totalUnits,omitempty"`
	WeeklyIncreaseUnits                          *int32   `protobuf:"varint,17,opt,name=weeklyIncreaseUnits" json:"weeklyIncreaseUnits,omitempty"`
	WeeklyIncreaseUnitsRate                      *float64 `protobuf:"fixed64,18,opt,name=weeklyIncreaseUnitsRate" json:"weeklyIncreaseUnitsRate,omitempty"`
	Code                                         int32    `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg                                          string   `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *DashboardGetDataOverviewResp) Reset() { *x = DashboardGetDataOverviewResp{} }

func (x *DashboardGetDataOverviewResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardGetDataOverviewResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardGetDataOverviewResp) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseUsers() int32 {
	if x != nil {
		return x.WeeklyIncreaseUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseUsersRate() float64 {
	if x != nil {
		return x.WeeklyIncreaseUsersRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetActiveUsers() int32 {
	if x != nil && x.ActiveUsers != nil {
		return *x.ActiveUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseActiveUsers() int32 {
	if x != nil && x.WeeklyIncreaseActiveUsers != nil {
		return *x.WeeklyIncreaseActiveUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseActiveUsersRate() float64 {
	if x != nil && x.WeeklyIncreaseActiveUsersRate != nil {
		return *x.WeeklyIncreaseActiveUsersRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetTotalConversations() int32 {
	if x != nil {
		return x.TotalConversations
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseConversations() int32 {
	if x != nil {
		return x.WeeklyIncreaseConversations
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseConversationsRate() float64 {
	if x != nil {
		return x.WeeklyIncreaseConversationsRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetAverageTimePerConversation() float64 {
	if x != nil {
		return x.AverageTimePerConversation
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseAverageTimePerConversation() float64 {
	if x != nil {
		return x.WeeklyIncreaseAverageTimePerConversation
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseAverageTimePerConversationRate() float64 {
	if x != nil {
		return x.WeeklyIncreaseAverageTimePerConversationRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetAlarmUsers() int32 {
	if x != nil {
		return x.AlarmUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseAlarmUsers() int32 {
	if x != nil {
		return x.WeeklyIncreaseAlarmUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseAlarmUsersRate() float64 {
	if x != nil {
		return x.WeeklyIncreaseAlarmUsersRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetTotalUnits() int32 {
	if x != nil && x.TotalUnits != nil {
		return *x.TotalUnits
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseUnits() int32 {
	if x != nil && x.WeeklyIncreaseUnits != nil {
		return *x.WeeklyIncreaseUnits
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseUnitsRate() float64 {
	if x != nil && x.WeeklyIncreaseUnitsRate != nil {
		return *x.WeeklyIncreaseUnitsRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 预警管理
type DashboardGetAlarmOverviewReq struct {
	UnitId string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
}

func (x *DashboardGetAlarmOverviewReq) Reset() { *x = DashboardGetAlarmOverviewReq{} }

func (x *DashboardGetAlarmOverviewReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardGetAlarmOverviewReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardGetAlarmOverviewReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type DashboardGetAlarmOverviewResp struct {
	Total           int32   `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`                      // 当前高风险用户总数
	Processed       int32   `protobuf:"varint,2,opt,name=processed" json:"processed,omitempty"`              // 当前已处理数
	Pending         int32   `protobuf:"varint,3,opt,name=pending" json:"pending,omitempty"`                  // 当前待处理数
	Track           int32   `protobuf:"varint,4,opt,name=track" json:"track,omitempty"`                      // 当前需追踪数
	TotalChange     float64 `protobuf:"fixed64,5,opt,name=totalChange" json:"totalChange,omitempty"`         // 对比上周总数变化百分比
	ProcessedChange float64 `protobuf:"fixed64,6,opt,name=processedChange" json:"processedChange,omitempty"` // 对比上周已处理变化百分比
	PendingChange   float64 `protobuf:"fixed64,7,opt,name=pendingChange" json:"pendingChange,omitempty"`     // 对比上周待处理变化百分比
	TrackChange     float64 `protobuf:"fixed64,8,opt,name=trackChange" json:"trackChange,omitempty"`         // 对比上周需追踪变化百分比
	Code            int32   `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg             string  `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *DashboardGetAlarmOverviewResp) Reset() { *x = DashboardGetAlarmOverviewResp{} }

func (x *DashboardGetAlarmOverviewResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardGetAlarmOverviewResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardGetAlarmOverviewResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetTrack() int32 {
	if x != nil {
		return x.Track
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetTotalChange() float64 {
	if x != nil {
		return x.TotalChange
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetProcessedChange() float64 {
	if x != nil {
		return x.ProcessedChange
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetPendingChange() float64 {
	if x != nil {
		return x.PendingChange
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetTrackChange() float64 {
	if x != nil {
		return x.TrackChange
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DashboardGetAlarmOverviewResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DashboardListAlarmRecordsReq struct {
	UnitId            string                   `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	Emotion           *string                  `protobuf:"bytes,2,opt,name=emotion" json:"emotion,omitempty"`
	Status            *string                  `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Keyword           *string                  `protobuf:"bytes,4,opt,name=keyword" json:"keyword,omitempty"`
	PaginationOptions *basic.PaginationOptions `protobuf:"bytes,5,opt,name=paginationOptions" json:"paginationOptions,omitempty"`
}

func (x *DashboardListAlarmRecordsReq) Reset() { *x = DashboardListAlarmRecordsReq{} }

func (x *DashboardListAlarmRecordsReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardListAlarmRecordsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardListAlarmRecordsReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *DashboardListAlarmRecordsReq) GetEmotion() string {
	if x != nil && x.Emotion != nil {
		return *x.Emotion
	}
	return ""
}

func (x *DashboardListAlarmRecordsReq) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *DashboardListAlarmRecordsReq) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *DashboardListAlarmRecordsReq) GetPaginationOptions() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOptions
	}
	return nil
}

type DashboardListAlarmRecordsResp struct {
	Records    []*AlarmRecord    `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	Pagination *basic.Pagination `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
	Code       int32             `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg        string            `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *DashboardListAlarmRecordsResp) Reset() { *x = DashboardListAlarmRecordsResp{} }

func (x *DashboardListAlarmRecordsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardListAlarmRecordsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardListAlarmRecordsResp) GetRecords() []*AlarmRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *DashboardListAlarmRecordsResp) GetPagination() *basic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *DashboardListAlarmRecordsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DashboardListAlarmRecordsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AlarmRecord struct {
	Id                      string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`                                            // 唯一Id
	Emotion                 string        `protobuf:"bytes,2,opt,name=emotion" json:"emotion,omitempty"`                                  // 情绪状态
	Keywords                []string      `protobuf:"bytes,3,rep,name=keywords" json:"keywords,omitempty"`                                // 关键词列表
	Status                  string        `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`                                    // 处理状态
	User                    *profile.User `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`                                        // 用户信息
	TotalConversationRounds int32         `protobuf:"varint,6,opt,name=totalConversationRounds" json:"totalConversationRounds,omitempty"` // 总对话轮数
	LastConversationTime    int64         `protobuf:"varint,7,opt,name=lastConversationTime" json:"lastConversationTime,omitempty"`       // 上次对话时间（分钟时间戳）
}

func (x *AlarmRecord) Reset() { *x = AlarmRecord{} }

func (x *AlarmRecord) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *AlarmRecord) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *AlarmRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlarmRecord) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *AlarmRecord) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *AlarmRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlarmRecord) GetUser() *profile.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AlarmRecord) GetTotalConversationRounds() int32 {
	if x != nil {
		return x.TotalConversationRounds
	}
	return 0
}

func (x *AlarmRecord) GetLastConversationTime() int64 {
	if x != nil {
		return x.LastConversationTime
	}
	return 0
}

// 用户管理
type ClassInfo struct {
	Class        int32  `protobuf:"varint,1,opt,name=class" json:"class,omitempty"`
	UserNum      int32  `protobuf:"varint,2,opt,name=UserNum" json:"UserNum,omitempty"`
	AlarmNum     int32  `protobuf:"varint,3,opt,name=alarmNum" json:"alarmNum,omitempty"`
	TeacherName  string `protobuf:"bytes,4,opt,name=teacherName" json:"teacherName,omitempty"`
	TeacherPhone string `protobuf:"bytes,5,opt,name=teacherPhone" json:"teacherPhone,omitempty"`
}

func (x *ClassInfo) Reset() { *x = ClassInfo{} }

func (x *ClassInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ClassInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ClassInfo) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *ClassInfo) GetUserNum() int32 {
	if x != nil {
		return x.UserNum
	}
	return 0
}

func (x *ClassInfo) GetAlarmNum() int32 {
	if x != nil {
		return x.AlarmNum
	}
	return 0
}

func (x *ClassInfo) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *ClassInfo) GetTeacherPhone() string {
	if x != nil {
		return x.TeacherPhone
	}
	return ""
}

type GradeInfo struct {
	Grade   int32        `protobuf:"varint,1,opt,name=grade" json:"grade,omitempty"`
	Classes []*ClassInfo `protobuf:"bytes,2,rep,name=classes" json:"classes,omitempty"`
}

func (x *GradeInfo) Reset() { *x = GradeInfo{} }

func (x *GradeInfo) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GradeInfo) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GradeInfo) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *GradeInfo) GetClasses() []*ClassInfo {
	if x != nil {
		return x.Classes
	}
	return nil
}

type DashboardListClassesReq struct {
	UnitId string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	Grade  *int32 `protobuf:"varint,2,opt,name=grade" json:"grade,omitempty"`
	Class  *int32 `protobuf:"varint,3,opt,name=class" json:"class,omitempty"`
}

func (x *DashboardListClassesReq) Reset() { *x = DashboardListClassesReq{} }

func (x *DashboardListClassesReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardListClassesReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardListClassesReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *DashboardListClassesReq) GetGrade() int32 {
	if x != nil && x.Grade != nil {
		return *x.Grade
	}
	return 0
}

func (x *DashboardListClassesReq) GetClass() int32 {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return 0
}

type DashboardListClassesResp struct {
	Grades []*GradeInfo `protobuf:"bytes,1,rep,name=grades" json:"grades,omitempty"`
	Code   int32        `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg    string       `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *DashboardListClassesResp) Reset() { *x = DashboardListClassesResp{} }

func (x *DashboardListClassesResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardListClassesResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardListClassesResp) GetGrades() []*GradeInfo {
	if x != nil {
		return x.Grades
	}
	return nil
}

func (x *DashboardListClassesResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DashboardListClassesResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RiskUser struct {
	User                    *profile.User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Level                   int32         `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	TotalConversationRounds int32         `protobuf:"varint,3,opt,name=totalConversationRounds" json:"totalConversationRounds,omitempty"` // 总对话轮数
	LastConversationTime    int64         `protobuf:"varint,4,opt,name=lastConversationTime" json:"lastConversationTime,omitempty"`       // 上次对话时间（分钟时间戳）
	Keywords                []string      `protobuf:"bytes,5,rep,name=keywords" json:"keywords,omitempty"`
}

func (x *RiskUser) Reset() { *x = RiskUser{} }

func (x *RiskUser) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *RiskUser) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *RiskUser) GetUser() *profile.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RiskUser) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RiskUser) GetTotalConversationRounds() int32 {
	if x != nil {
		return x.TotalConversationRounds
	}
	return 0
}

func (x *RiskUser) GetLastConversationTime() int64 {
	if x != nil {
		return x.LastConversationTime
	}
	return 0
}

func (x *RiskUser) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type DashboardListUsersReq struct {
	UnitId            string                   `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	Level             *int32                   `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Gender            *string                  `protobuf:"bytes,3,opt,name=gender" json:"gender,omitempty"`
	Keyword           *string                  `protobuf:"bytes,4,opt,name=keyword" json:"keyword,omitempty"`
	PaginationOptions *basic.PaginationOptions `protobuf:"bytes,5,opt,name=paginationOptions" json:"paginationOptions,omitempty"`
}

func (x *DashboardListUsersReq) Reset() { *x = DashboardListUsersReq{} }

func (x *DashboardListUsersReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardListUsersReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardListUsersReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *DashboardListUsersReq) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *DashboardListUsersReq) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *DashboardListUsersReq) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *DashboardListUsersReq) GetPaginationOptions() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOptions
	}
	return nil
}

type DashboardListUsersResp struct {
	RiskUsers  []*RiskUser       `protobuf:"bytes,1,rep,name=riskUsers" json:"riskUsers,omitempty"`
	Pagination *basic.Pagination `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
	Code       int32             `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg        string            `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *DashboardListUsersResp) Reset() { *x = DashboardListUsersResp{} }

func (x *DashboardListUsersResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardListUsersResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardListUsersResp) GetRiskUsers() []*RiskUser {
	if x != nil {
		return x.RiskUsers
	}
	return nil
}

func (x *DashboardListUsersResp) GetPagination() *basic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *DashboardListUsersResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DashboardListUsersResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}
