// Code generated by Kitex v0.15.4. DO NOT EDIT.

package core_api

import (
	"github.com/xh-polaris/psych-idl/kitex_gen/profile"

	"github.com/cloudwego/prutal"
)

type UserSignInReq struct {
	UnitId     string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	AuthType   int32  `protobuf:"varint,2,opt,name=authType" json:"authType,omitempty"`
	AuthId     string `protobuf:"bytes,3,opt,name=authId" json:"authId,omitempty"`
	VerifyCode string `protobuf:"bytes,4,opt,name=verifyCode" json:"verifyCode,omitempty"`
}

func (x *UserSignInReq) Reset() { *x = UserSignInReq{} }

func (x *UserSignInReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserSignInReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserSignInReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UserSignInReq) GetAuthType() int32 {
	if x != nil {
		return x.AuthType
	}
	return 0
}

func (x *UserSignInReq) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *UserSignInReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type UserSignInResp struct {
	UnitId    string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	CodeType  string `protobuf:"bytes,3,opt,name=codeType" json:"codeType,omitempty"`
	CodeValue string `protobuf:"bytes,4,opt,name=codeValue" json:"codeValue,omitempty"`
	Token     string `protobuf:"bytes,5,opt,name=token" json:"token,omitempty"`
	Code      int32  `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg       string `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UserSignInResp) Reset() { *x = UserSignInResp{} }

func (x *UserSignInResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserSignInResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserSignInResp) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UserSignInResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSignInResp) GetCodeType() string {
	if x != nil {
		return x.CodeType
	}
	return ""
}

func (x *UserSignInResp) GetCodeValue() string {
	if x != nil {
		return x.CodeValue
	}
	return ""
}

func (x *UserSignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserSignInResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserSignInResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取信息
type UserGetInfoReq struct {
}

func (x *UserGetInfoReq) Reset() { *x = UserGetInfoReq{} }

func (x *UserGetInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserGetInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type UserGetInfoResp struct {
	User *profile.User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Code int32         `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg  string        `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UserGetInfoResp) Reset() { *x = UserGetInfoResp{} }

func (x *UserGetInfoResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UserGetInfoResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UserGetInfoResp) GetUser() *profile.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserGetInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserGetInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 数据看板
type DashboardGetDataOverviewReq struct {
	UnitId *string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
}

func (x *DashboardGetDataOverviewReq) Reset() { *x = DashboardGetDataOverviewReq{} }

func (x *DashboardGetDataOverviewReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardGetDataOverviewReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardGetDataOverviewReq) GetUnitId() string {
	if x != nil && x.UnitId != nil {
		return *x.UnitId
	}
	return ""
}

type DashboardGetDataOverviewResp struct {
	TotalUsers                                   int32    `protobuf:"varint,1,opt,name=totalUsers" json:"totalUsers,omitempty"`
	WeeklyIncreaseUsers                          int32    `protobuf:"varint,2,opt,name=weeklyIncreaseUsers" json:"weeklyIncreaseUsers,omitempty"`
	WeeklyIncreaseUsersRate                      float64  `protobuf:"fixed64,3,opt,name=weeklyIncreaseUsersRate" json:"weeklyIncreaseUsersRate,omitempty"`
	ActiveUsers                                  *int32   `protobuf:"varint,4,opt,name=activeUsers" json:"activeUsers,omitempty"`
	WeeklyIncreaseActiveUsers                    *int32   `protobuf:"varint,5,opt,name=weeklyIncreaseActiveUsers" json:"weeklyIncreaseActiveUsers,omitempty"`
	WeeklyIncreaseActiveUsersRate                *float64 `protobuf:"fixed64,6,opt,name=weeklyIncreaseActiveUsersRate" json:"weeklyIncreaseActiveUsersRate,omitempty"`
	TotalConversations                           int32    `protobuf:"varint,7,opt,name=totalConversations" json:"totalConversations,omitempty"`
	WeeklyIncreaseConversations                  int32    `protobuf:"varint,8,opt,name=weeklyIncreaseConversations" json:"weeklyIncreaseConversations,omitempty"`
	WeeklyIncreaseConversationsRate              float64  `protobuf:"fixed64,9,opt,name=weeklyIncreaseConversationsRate" json:"weeklyIncreaseConversationsRate,omitempty"`
	AverageTimePerConversation                   float64  `protobuf:"fixed64,10,opt,name=averageTimePerConversation" json:"averageTimePerConversation,omitempty"`                             // minutes
	WeeklyIncreaseAverageTimePerConversation     float64  `protobuf:"fixed64,11,opt,name=weeklyIncreaseAverageTimePerConversation" json:"weeklyIncreaseAverageTimePerConversation,omitempty"` // minutes
	WeeklyIncreaseAverageTimePerConversationRate float64  `protobuf:"fixed64,12,opt,name=weeklyIncreaseAverageTimePerConversationRate" json:"weeklyIncreaseAverageTimePerConversationRate,omitempty"`
	AlarmUsers                                   int32    `protobuf:"varint,13,opt,name=alarmUsers" json:"alarmUsers,omitempty"`
	WeeklyIncreaseAlarmUsers                     int32    `protobuf:"varint,14,opt,name=weeklyIncreaseAlarmUsers" json:"weeklyIncreaseAlarmUsers,omitempty"`
	WeeklyIncreaseAlarmUsersRate                 float64  `protobuf:"fixed64,15,opt,name=weeklyIncreaseAlarmUsersRate" json:"weeklyIncreaseAlarmUsersRate,omitempty"`
	TotalUnits                                   *int32   `protobuf:"varint,16,opt,name=totalUnits" json:"totalUnits,omitempty"`
	WeeklyIncreaseUnits                          *int32   `protobuf:"varint,17,opt,name=weeklyIncreaseUnits" json:"weeklyIncreaseUnits,omitempty"`
	WeeklyIncreaseUnitsRate                      *float64 `protobuf:"fixed64,18,opt,name=weeklyIncreaseUnitsRate" json:"weeklyIncreaseUnitsRate,omitempty"`
	Code                                         int32    `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg                                          string   `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *DashboardGetDataOverviewResp) Reset() { *x = DashboardGetDataOverviewResp{} }

func (x *DashboardGetDataOverviewResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *DashboardGetDataOverviewResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DashboardGetDataOverviewResp) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseUsers() int32 {
	if x != nil {
		return x.WeeklyIncreaseUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseUsersRate() float64 {
	if x != nil {
		return x.WeeklyIncreaseUsersRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetActiveUsers() int32 {
	if x != nil && x.ActiveUsers != nil {
		return *x.ActiveUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseActiveUsers() int32 {
	if x != nil && x.WeeklyIncreaseActiveUsers != nil {
		return *x.WeeklyIncreaseActiveUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseActiveUsersRate() float64 {
	if x != nil && x.WeeklyIncreaseActiveUsersRate != nil {
		return *x.WeeklyIncreaseActiveUsersRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetTotalConversations() int32 {
	if x != nil {
		return x.TotalConversations
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseConversations() int32 {
	if x != nil {
		return x.WeeklyIncreaseConversations
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseConversationsRate() float64 {
	if x != nil {
		return x.WeeklyIncreaseConversationsRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetAverageTimePerConversation() float64 {
	if x != nil {
		return x.AverageTimePerConversation
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseAverageTimePerConversation() float64 {
	if x != nil {
		return x.WeeklyIncreaseAverageTimePerConversation
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseAverageTimePerConversationRate() float64 {
	if x != nil {
		return x.WeeklyIncreaseAverageTimePerConversationRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetAlarmUsers() int32 {
	if x != nil {
		return x.AlarmUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseAlarmUsers() int32 {
	if x != nil {
		return x.WeeklyIncreaseAlarmUsers
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseAlarmUsersRate() float64 {
	if x != nil {
		return x.WeeklyIncreaseAlarmUsersRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetTotalUnits() int32 {
	if x != nil && x.TotalUnits != nil {
		return *x.TotalUnits
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseUnits() int32 {
	if x != nil && x.WeeklyIncreaseUnits != nil {
		return *x.WeeklyIncreaseUnits
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetWeeklyIncreaseUnitsRate() float64 {
	if x != nil && x.WeeklyIncreaseUnitsRate != nil {
		return *x.WeeklyIncreaseUnitsRate
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DashboardGetDataOverviewResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}
