// Code generated by Kitex v0.16.2. DO NOT EDIT.

package core_api

import (
	"github.com/xh-polaris/psych-idl/kitex_gen/basic"

	"github.com/cloudwego/prutal"
)

// 新建对话
type CreateConversationReq struct {
}

func (x *CreateConversationReq) Reset() { *x = CreateConversationReq{} }

func (x *CreateConversationReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateConversationReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

type CreateConversationResp struct {
	ConversationId string `protobuf:"bytes,1,opt,name=conversationId" json:"conversationId,omitempty"`
	Code           int32  `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg            string `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *CreateConversationResp) Reset() { *x = CreateConversationResp{} }

func (x *CreateConversationResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *CreateConversationResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateConversationResp) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CreateConversationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateConversationResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 对话列表
type ListConversationsReq struct {
	PaginationOptions *basic.PaginationOptions `protobuf:"bytes,1,opt,name=paginationOptions" json:"paginationOptions,omitempty"`
	StartDate         string                   `protobuf:"bytes,2,opt,name=startDate" json:"startDate,omitempty"`
	EndDate           string                   `protobuf:"bytes,3,opt,name=endDate" json:"endDate,omitempty"`
}

func (x *ListConversationsReq) Reset() { *x = ListConversationsReq{} }

func (x *ListConversationsReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ListConversationsReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListConversationsReq) GetPaginationOptions() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOptions
	}
	return nil
}

func (x *ListConversationsReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListConversationsReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ListConversationsResp struct {
	ConversationList []*ConversationVO `protobuf:"bytes,1,rep,name=conversationList" json:"conversationList,omitempty"`
	Pagination       *basic.Pagination `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
	Code             int32             `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg              string            `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *ListConversationsResp) Reset() { *x = ListConversationsResp{} }

func (x *ListConversationsResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *ListConversationsResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ListConversationsResp) GetConversationList() []*ConversationVO {
	if x != nil {
		return x.ConversationList
	}
	return nil
}

func (x *ListConversationsResp) GetPagination() *basic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListConversationsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListConversationsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获得单次对话下的历史消息
type GetSingleConvReq struct {
	PaginationOptions *basic.PaginationOptions `protobuf:"bytes,1,opt,name=paginationOptions" json:"paginationOptions,omitempty"`
	ConversationId    string                   `protobuf:"bytes,2,opt,name=conversationId" json:"conversationId,omitempty"`
}

func (x *GetSingleConvReq) Reset() { *x = GetSingleConvReq{} }

func (x *GetSingleConvReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetSingleConvReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSingleConvReq) GetPaginationOptions() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOptions
	}
	return nil
}

func (x *GetSingleConvReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetSingleConvResp struct {
	Pagination  *basic.Pagination `protobuf:"bytes,1,opt,name=pagination" json:"pagination,omitempty"`
	MessageList []*Message        `protobuf:"bytes,2,rep,name=messageList" json:"messageList,omitempty"`
	Code        int32             `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg         string            `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *GetSingleConvResp) Reset() { *x = GetSingleConvResp{} }

func (x *GetSingleConvResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetSingleConvResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetSingleConvResp) GetPagination() *basic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetSingleConvResp) GetMessageList() []*Message {
	if x != nil {
		return x.MessageList
	}
	return nil
}

func (x *GetSingleConvResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSingleConvResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ConversationVO struct {
	ConversationId string `protobuf:"bytes,1,opt,name=conversationId" json:"conversationId,omitempty"`
	Brief          string `protobuf:"bytes,2,opt,name=brief" json:"brief,omitempty"`
	CreateTime     int64  `protobuf:"varint,3,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime     int64  `protobuf:"varint,4,opt,name=updateTime" json:"updateTime,omitempty"`
	Date           string `protobuf:"bytes,5,opt,name=date" json:"date,omitempty"`
}

func (x *ConversationVO) Reset() { *x = ConversationVO{} }

func (x *ConversationVO) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ConversationVO) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ConversationVO) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationVO) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *ConversationVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ConversationVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *ConversationVO) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Message struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`

	// 角色, system/assistant/user/tool, 依次为1,2,3,4
	Role int32 `protobuf:"varint,2,opt,name=role" json:"role,omitempty"`

	// 消息索引
	Index int32 `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
}

func (x *Message) Reset() { *x = Message{} }

func (x *Message) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Message) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *Message) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 按天获取用户所有对话消息
type GetConvByDateReq struct {
	PaginationOptions *basic.PaginationOptions `protobuf:"bytes,1,opt,name=paginationOptions" json:"paginationOptions,omitempty"`
	Date              string                   `protobuf:"bytes,2,opt,name=date" json:"date,omitempty"`
	UserId            string                   `protobuf:"bytes,3,opt,name=userId" json:"userId,omitempty"`
}

func (x *GetConvByDateReq) Reset() { *x = GetConvByDateReq{} }

func (x *GetConvByDateReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetConvByDateReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetConvByDateReq) GetPaginationOptions() *basic.PaginationOptions {
	if x != nil {
		return x.PaginationOptions
	}
	return nil
}

func (x *GetConvByDateReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetConvByDateReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetConvByDateResp struct {
	Pagination  *basic.Pagination    `protobuf:"bytes,1,opt,name=pagination" json:"pagination,omitempty"`
	MessageList []*ConvByDateMessage `protobuf:"bytes,2,rep,name=messageList" json:"messageList,omitempty"`
	Code        int32                `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg         string               `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *GetConvByDateResp) Reset() { *x = GetConvByDateResp{} }

func (x *GetConvByDateResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetConvByDateResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetConvByDateResp) GetPagination() *basic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetConvByDateResp) GetMessageList() []*ConvByDateMessage {
	if x != nil {
		return x.MessageList
	}
	return nil
}

func (x *GetConvByDateResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetConvByDateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ConvByDateMessage struct {
	ConversationId string `protobuf:"bytes,1,opt,name=conversationId" json:"conversationId,omitempty"`
	Content        string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Role           int32  `protobuf:"varint,3,opt,name=role" json:"role,omitempty"`
	Index          int32  `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	CreateTime     int64  `protobuf:"varint,5,opt,name=createTime" json:"createTime,omitempty"`
}

func (x *ConvByDateMessage) Reset() { *x = ConvByDateMessage{} }

func (x *ConvByDateMessage) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ConvByDateMessage) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ConvByDateMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConvByDateMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConvByDateMessage) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *ConvByDateMessage) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ConvByDateMessage) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// SSEEvent
type SSEEvent struct {
	// 事件数据
	EventData string `protobuf:"bytes,1,opt,name=eventData" json:"eventData,omitempty"`

	// 事件id
	EventId int32 `protobuf:"varint,2,opt,name=eventId" json:"eventId,omitempty"`

	// 事件类型
	EventType int32 `protobuf:"varint,3,opt,name=eventType" json:"eventType,omitempty"`
}

func (x *SSEEvent) Reset() { *x = SSEEvent{} }

func (x *SSEEvent) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *SSEEvent) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *SSEEvent) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

func (x *SSEEvent) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *SSEEvent) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}
