// Code generated by Kitex v0.15.2. DO NOT EDIT.

package core_api

import "context"

type CoreApi interface {
	UserSignIn(ctx context.Context, req *UserSignInReq) (res *UserSignInResp, err error)
	UserGetInfo(ctx context.Context, req *UserGetInfoReq) (res *UserGetInfoResp, err error)
}
