// Code generated by Kitex v0.16.1. DO NOT EDIT.

package core_api

import (
	"context"
	"github.com/xh-polaris/psych-idl/kitex_gen/basic"
)

type User interface {
	UserSignIn(ctx context.Context, req *UserSignInReq) (res *UserSignInResp, err error)
	UserGetInfo(ctx context.Context, req *UserGetInfoReq) (res *UserGetInfoResp, err error)
	UserUpdateInfo(ctx context.Context, req *UserUpdateInfoReq) (res *basic.Response, err error)
	UserUpdatePassword(ctx context.Context, req *UserUpdatePasswordReq) (res *basic.Response, err error)
}

type Unit interface {
	UnitGetInfo(ctx context.Context, req *UnitGetInfoReq) (res *UnitGetInfoResp, err error)
	UnitUpdateInfo(ctx context.Context, req *UnitUpdateInfoReq) (res *basic.Response, err error)
	UnitLinkUser(ctx context.Context, req *UnitLinkUserReq) (res *basic.Response, err error)
	UnitCreateAndLinkUser(ctx context.Context, req *UnitCreateAndLinkUserReq) (res *UnitCreateAndLinkUserResp, err error)
}

type Config interface {
	ConfigCreate(ctx context.Context, req *ConfigCreateOrUpdateReq) (res *basic.Response, err error)
	ConfigUpdateInfo(ctx context.Context, req *ConfigCreateOrUpdateReq) (res *basic.Response, err error)
	ConfigGetByUnitID(ctx context.Context, req *ConfigGetByUnitIdReq) (res *ConfigGetByUnitIdResp, err error)
}

type Dashboard interface {
	DashboardGetDataOverview(ctx context.Context, req *DashboardGetDataOverviewReq) (res *DashboardGetDataOverviewResp, err error)
	DashboardGetDataTrend(ctx context.Context, req *DashboardGetDataTrendReq) (res *DashboardGetDataTrendResp, err error)
	DashboardListUnits(ctx context.Context, req *DashboardListUnitsReq) (res *DashboardListUnitsResp, err error)
	DashboardGetPsychTrend(ctx context.Context, req *DashboardGetPsychTrendReq) (res *DashboardGetPsychTrendResp, err error)
	DashboardGetAlarmOverview(ctx context.Context, req *DashboardGetAlarmOverviewReq) (res *DashboardGetAlarmOverviewResp, err error)
	DashboardListAlarmRecords(ctx context.Context, req *DashboardListAlarmRecordsReq) (res *DashboardListAlarmRecordsResp, err error)
	DashboardUpdateAlarm(ctx context.Context, req *DashboardUpdateAlarmReq) (res *DashboardUpdateAlarmResp, err error)
	DashboardListClasses(ctx context.Context, req *DashboardListClassesReq) (res *DashboardListClassesResp, err error)
	DashboardListUsers(ctx context.Context, req *DashboardListUsersReq) (res *DashboardListUsersResp, err error)
	DashboardUserConvRecords(ctx context.Context, req *DashboardUserConvRecordsReq) (res *DashboardUserConvRecordsResp, err error)
	DashboardUnitConvRecords(ctx context.Context, req *DashboardUnitConvRecordsReq) (res *DashboardUnitConvRecordsResp, err error)
	DashboardGetReport(ctx context.Context, req *DashboardGetReportReq) (res *DashboardGetReportResp, err error)
}

type Conversation interface {
	CreateConversation(ctx context.Context, req *CreateConversationReq) (res *CreateConversationResp, err error)
	ListConversations(ctx context.Context, req *ListConversationsReq) (res *ListConversationsResp, err error)
	GetConversation(ctx context.Context, req *GetConversationReq) (res *GetConversationResp, err error)
}
