// Code generated by Kitex v0.15.4. DO NOT EDIT.

package core_api

import "context"

type PsychDashboardService interface {
	DashboardGetDataOverview(ctx context.Context, req *DashboardGetDataOverviewReq) (res *DashboardGetDataOverviewResp, err error)
	DashboardGetAlarmOverview(ctx context.Context, req *DashboardGetAlarmOverviewReq) (res *DashboardGetAlarmOverviewResp, err error)
	DashboardListAlarmUsers(ctx context.Context, req *DashboardListAlarmRecordsReq) (res *DashboardListAlarmRecordsReq, err error)
	DashboardListClasses(ctx context.Context, req *DashboardListClassesReq) (res *DashboardListClassesResp, err error)
	DashboardListUsers(ctx context.Context, req *DashboardListUsersReq) (res *DashboardListUsersResp, err error)
}
