// Code generated by Kitex v0.16.3. DO NOT EDIT.

package core_api

import "github.com/cloudwego/prutal"

type OpenApiChatMessage struct {
	// 仅支持 user / assistant，最后一条必须为非空 user
	Role string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`

	// 消息文本，非空
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (x *OpenApiChatMessage) Reset() { *x = OpenApiChatMessage{} }

func (x *OpenApiChatMessage) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OpenApiChatMessage) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *OpenApiChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type OpenApiChatMetadata struct {
	// 调用方用户关联 ID，仅作关联标记，不用于查询服务端历史
	ExternalUserId string `protobuf:"bytes,1,opt,name=external_user_id" json:"external_user_id,omitempty"`
}

func (x *OpenApiChatMetadata) Reset() { *x = OpenApiChatMetadata{} }

func (x *OpenApiChatMetadata) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OpenApiChatMetadata) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiChatMetadata) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

type OpenApiChatCompletionReq struct {
	// 当前固定 psych-chat-v1
	Model string `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`

	// 完整对话上下文，按时间正序
	Messages []*OpenApiChatMessage `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty"`

	// 必须为 true，非流式返回 400 unsupported_stream_mode
	Stream bool `protobuf:"varint,3,opt,name=stream" json:"stream,omitempty"`

	// 单次回复最大 token 数
	MaxTokens *int32 `protobuf:"varint,4,opt,name=max_tokens" json:"max_tokens,omitempty"`

	// 采样温度 0~2，超范围返回 400
	Temperature *float64 `protobuf:"fixed64,5,opt,name=temperature" json:"temperature,omitempty"`

	// 白名单关联信息
	Metadata *OpenApiChatMetadata `protobuf:"bytes,6,opt,name=metadata" json:"metadata,omitempty"`
}

func (x *OpenApiChatCompletionReq) Reset() { *x = OpenApiChatCompletionReq{} }

func (x *OpenApiChatCompletionReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *OpenApiChatCompletionReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiChatCompletionReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OpenApiChatCompletionReq) GetMessages() []*OpenApiChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *OpenApiChatCompletionReq) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *OpenApiChatCompletionReq) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *OpenApiChatCompletionReq) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *OpenApiChatCompletionReq) GetMetadata() *OpenApiChatMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type OpenApiChatCompletionResp struct {
	// 平台请求 ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id" json:"request_id,omitempty"`

	// 错误码，成功为空；取值见接口文档错误码表
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`

	// 错误信息
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (x *OpenApiChatCompletionResp) Reset() { *x = OpenApiChatCompletionResp{} }

func (x *OpenApiChatCompletionResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *OpenApiChatCompletionResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiChatCompletionResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpenApiChatCompletionResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OpenApiChatCompletionResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 第三方报告接口使用的匿名受访者画像。
type OpenApiSubjectProfile struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Grade  *int32 `protobuf:"varint,2,opt,name=grade" json:"grade,omitempty"`
	Class  *int32 `protobuf:"varint,3,opt,name=class" json:"class,omitempty"`
	Gender string `protobuf:"bytes,4,opt,name=gender" json:"gender,omitempty"`
}

func (x *OpenApiSubjectProfile) Reset() { *x = OpenApiSubjectProfile{} }

func (x *OpenApiSubjectProfile) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *OpenApiSubjectProfile) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiSubjectProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenApiSubjectProfile) GetGrade() int32 {
	if x != nil && x.Grade != nil {
		return *x.Grade
	}
	return 0
}

func (x *OpenApiSubjectProfile) GetClass() int32 {
	if x != nil && x.Class != nil {
		return *x.Class
	}
	return 0
}

func (x *OpenApiSubjectProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

// 开放接口用量结构。
type OpenApiUsage struct {
	PromptTokens     int32 `protobuf:"varint,1,opt,name=prompt_tokens" json:"prompt_tokens,omitempty"`
	CompletionTokens int32 `protobuf:"varint,2,opt,name=completion_tokens" json:"completion_tokens,omitempty"`
	TotalTokens      int32 `protobuf:"varint,3,opt,name=total_tokens" json:"total_tokens,omitempty"`
}

func (x *OpenApiUsage) Reset() { *x = OpenApiUsage{} }

func (x *OpenApiUsage) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OpenApiUsage) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *OpenApiUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *OpenApiUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// 开放接口返回的报告值对象，不包含平台持久化字段。
type OpenApiReport struct {
	Title        string           `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Digest       string           `protobuf:"bytes,2,opt,name=digest" json:"digest,omitempty"`
	NeedAlarm    bool             `protobuf:"varint,3,opt,name=need_alarm" json:"need_alarm,omitempty"`
	Analysis     *ReportAnalysis  `protobuf:"bytes,4,opt,name=analysis" json:"analysis,omitempty"`
	SimpleReport *SimpleReportMsg `protobuf:"bytes,5,opt,name=simple_report" json:"simple_report,omitempty"`
}

func (x *OpenApiReport) Reset() { *x = OpenApiReport{} }

func (x *OpenApiReport) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *OpenApiReport) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiReport) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OpenApiReport) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *OpenApiReport) GetNeedAlarm() bool {
	if x != nil {
		return x.NeedAlarm
	}
	return false
}

func (x *OpenApiReport) GetAnalysis() *ReportAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *OpenApiReport) GetSimpleReport() *SimpleReportMsg {
	if x != nil {
		return x.SimpleReport
	}
	return nil
}

type OpenApiGenerateReportReq struct {
	Model          string                 `protobuf:"bytes,1,opt,name=model" json:"model,omitempty"`
	Messages       []*OpenApiChatMessage  `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty"`
	SubjectProfile *OpenApiSubjectProfile `protobuf:"bytes,3,opt,name=subject_profile" json:"subject_profile,omitempty"`
	MaxTokens      *int32                 `protobuf:"varint,4,opt,name=max_tokens" json:"max_tokens,omitempty"`
	Metadata       *OpenApiChatMetadata   `protobuf:"bytes,5,opt,name=metadata" json:"metadata,omitempty"`
}

func (x *OpenApiGenerateReportReq) Reset() { *x = OpenApiGenerateReportReq{} }

func (x *OpenApiGenerateReportReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *OpenApiGenerateReportReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiGenerateReportReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OpenApiGenerateReportReq) GetMessages() []*OpenApiChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *OpenApiGenerateReportReq) GetSubjectProfile() *OpenApiSubjectProfile {
	if x != nil {
		return x.SubjectProfile
	}
	return nil
}

func (x *OpenApiGenerateReportReq) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *OpenApiGenerateReportReq) GetMetadata() *OpenApiChatMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type OpenApiGenerateReportResp struct {
	Id          string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RequestId   string         `protobuf:"bytes,2,opt,name=request_id" json:"request_id,omitempty"`
	Object      string         `protobuf:"bytes,3,opt,name=object" json:"object,omitempty"`
	Created     int64          `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	Model       string         `protobuf:"bytes,5,opt,name=model" json:"model,omitempty"`
	Report      *OpenApiReport `protobuf:"bytes,6,opt,name=report" json:"report,omitempty"`
	Usage       *OpenApiUsage  `protobuf:"bytes,7,opt,name=usage" json:"usage,omitempty"`
	UsageSource string         `protobuf:"bytes,8,opt,name=usage_source" json:"usage_source,omitempty"`
}

func (x *OpenApiGenerateReportResp) Reset() { *x = OpenApiGenerateReportResp{} }

func (x *OpenApiGenerateReportResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *OpenApiGenerateReportResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *OpenApiGenerateReportResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpenApiGenerateReportResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OpenApiGenerateReportResp) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *OpenApiGenerateReportResp) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *OpenApiGenerateReportResp) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OpenApiGenerateReportResp) GetReport() *OpenApiReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *OpenApiGenerateReportResp) GetUsage() *OpenApiUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *OpenApiGenerateReportResp) GetUsageSource() string {
	if x != nil {
		return x.UsageSource
	}
	return ""
}
