// Code generated by Kitex v0.16.1. DO NOT EDIT.

package core_api

import "github.com/cloudwego/prutal"

type UnitVO struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Phone      string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Address    string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Contact    string `protobuf:"bytes,6,opt,name=contact" json:"contact,omitempty"`
	Level      int32  `protobuf:"varint,7,opt,name=level" json:"level,omitempty"`
	Status     string `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
	CreateTime int64  `protobuf:"varint,9,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime int64  `protobuf:"varint,10,opt,name=updateTime" json:"updateTime,omitempty"`
	DeleteTime int64  `protobuf:"varint,11,opt,name=deleteTime" json:"deleteTime,omitempty"`
}

func (x *UnitVO) Reset() { *x = UnitVO{} }

func (x *UnitVO) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitVO) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitVO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnitVO) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UnitVO) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UnitVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitVO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UnitVO) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *UnitVO) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UnitVO) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnitVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UnitVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *UnitVO) GetDeleteTime() int64 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

// 登录相关
type UnitSignInReq struct {
	AuthType   int32  `protobuf:"varint,1,opt,name=authType" json:"authType,omitempty"`
	AuthId     string `protobuf:"bytes,2,opt,name=authId" json:"authId,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	UnitId     string `protobuf:"bytes,4,opt,name=unitId" json:"unitId,omitempty"` // 后续改成unitName，用synapse的Query Unit获得unitId
}

func (x *UnitSignInReq) Reset() { *x = UnitSignInReq{} }

func (x *UnitSignInReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitSignInReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitSignInReq) GetAuthType() int32 {
	if x != nil {
		return x.AuthType
	}
	return 0
}

func (x *UnitSignInReq) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *UnitSignInReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *UnitSignInReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type UnitSignInResp struct {
	UnitId string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Code   int32  `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg    string `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UnitSignInResp) Reset() { *x = UnitSignInResp{} }

func (x *UnitSignInResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitSignInResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitSignInResp) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UnitSignInResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UnitSignInResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnitSignInResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取信息
type UnitGetInfoReq struct {
	UnitId string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
}

func (x *UnitGetInfoReq) Reset() { *x = UnitGetInfoReq{} }

func (x *UnitGetInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitGetInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitGetInfoReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type UnitGetInfoResp struct {
	Unit *UnitVO `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
	Code int32   `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UnitGetInfoResp) Reset() { *x = UnitGetInfoResp{} }

func (x *UnitGetInfoResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitGetInfoResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitGetInfoResp) GetUnit() *UnitVO {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *UnitGetInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnitGetInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 更新信息
type UnitUpdateInfoReq struct {
	Unit *UnitVO `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
}

func (x *UnitUpdateInfoReq) Reset() { *x = UnitUpdateInfoReq{} }

func (x *UnitUpdateInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitUpdateInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitUpdateInfoReq) GetUnit() *UnitVO {
	if x != nil {
		return x.Unit
	}
	return nil
}

// 更新密码
type UnitUpdatePasswordReq struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	AuthType    int32  `protobuf:"varint,2,opt,name=authType" json:"authType,omitempty"`
	VerifyCode  string `protobuf:"bytes,3,opt,name=verifyCode" json:"verifyCode,omitempty"`
	NewPassword string `protobuf:"bytes,4,opt,name=newPassword" json:"newPassword,omitempty"`
}

func (x *UnitUpdatePasswordReq) Reset() { *x = UnitUpdatePasswordReq{} }

func (x *UnitUpdatePasswordReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UnitUpdatePasswordReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitUpdatePasswordReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnitUpdatePasswordReq) GetAuthType() int32 {
	if x != nil {
		return x.AuthType
	}
	return 0
}

func (x *UnitUpdatePasswordReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *UnitUpdatePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// 关联用户
type UnitLinkUserReq struct {
	UnitId string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
}

func (x *UnitLinkUserReq) Reset() { *x = UnitLinkUserReq{} }

func (x *UnitLinkUserReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitLinkUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitLinkUserReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UnitLinkUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 创建并关联用户
type UnitCreateAndLinkUserReq struct {
	UnitId   string    `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
	CodeType string    `protobuf:"bytes,2,opt,name=codeType" json:"codeType,omitempty"`
	Users    []*UserVO `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
}

func (x *UnitCreateAndLinkUserReq) Reset() { *x = UnitCreateAndLinkUserReq{} }

func (x *UnitCreateAndLinkUserReq) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UnitCreateAndLinkUserReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitCreateAndLinkUserReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *UnitCreateAndLinkUserReq) GetCodeType() string {
	if x != nil {
		return x.CodeType
	}
	return ""
}

func (x *UnitCreateAndLinkUserReq) GetUsers() []*UserVO {
	if x != nil {
		return x.Users
	}
	return nil
}

type UnitCreateAndLinkUserResp struct {
	AllCount     int32  `protobuf:"varint,1,opt,name=allCount" json:"allCount,omitempty"`
	SuccessCount int32  `protobuf:"varint,2,opt,name=successCount" json:"successCount,omitempty"`
	SkipCount    int32  `protobuf:"varint,3,opt,name=skipCount" json:"skipCount,omitempty"`
	Code         int32  `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg          string `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UnitCreateAndLinkUserResp) Reset() { *x = UnitCreateAndLinkUserResp{} }

func (x *UnitCreateAndLinkUserResp) Marshal(in []byte) ([]byte, error) {
	return prutal.MarshalAppend(in, x)
}

func (x *UnitCreateAndLinkUserResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitCreateAndLinkUserResp) GetAllCount() int32 {
	if x != nil {
		return x.AllCount
	}
	return 0
}

func (x *UnitCreateAndLinkUserResp) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *UnitCreateAndLinkUserResp) GetSkipCount() int32 {
	if x != nil {
		return x.SkipCount
	}
	return 0
}

func (x *UnitCreateAndLinkUserResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnitCreateAndLinkUserResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}
