// Code generated by Kitex v0.16.1. DO NOT EDIT.

package core_api

import "github.com/cloudwego/prutal"

type UnitVO struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Address string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Contact string `protobuf:"bytes,6,opt,name=contact" json:"contact,omitempty"`
	Level   int32  `protobuf:"varint,7,opt,name=level" json:"level,omitempty"`

	// 1-2: Active | Deleted
	Status     int32  `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
	CreateTime int64  `protobuf:"varint,9,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime int64  `protobuf:"varint,10,opt,name=updateTime" json:"updateTime,omitempty"`
	DeleteTime int64  `protobuf:"varint,11,opt,name=deleteTime" json:"deleteTime,omitempty"`
	Uri        string `protobuf:"bytes,12,opt,name=uri" json:"uri,omitempty"`
}

func (x *UnitVO) Reset() { *x = UnitVO{} }

func (x *UnitVO) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitVO) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitVO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnitVO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnitVO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UnitVO) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *UnitVO) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UnitVO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UnitVO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UnitVO) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *UnitVO) GetDeleteTime() int64 {
	if x != nil {
		return x.DeleteTime
	}
	return 0
}

func (x *UnitVO) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

// 获取信息
type UnitGetInfoReq struct {
	UnitId string `protobuf:"bytes,1,opt,name=unitId" json:"unitId,omitempty"`
}

func (x *UnitGetInfoReq) Reset() { *x = UnitGetInfoReq{} }

func (x *UnitGetInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitGetInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitGetInfoReq) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type UnitGetInfoResp struct {
	Unit *UnitVO `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
	Code int32   `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UnitGetInfoResp) Reset() { *x = UnitGetInfoResp{} }

func (x *UnitGetInfoResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitGetInfoResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitGetInfoResp) GetUnit() *UnitVO {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *UnitGetInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnitGetInfoResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 更新信息
type UnitUpdateInfoReq struct {
	Unit *UnitVO `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
}

func (x *UnitUpdateInfoReq) Reset() { *x = UnitUpdateInfoReq{} }

func (x *UnitUpdateInfoReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitUpdateInfoReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitUpdateInfoReq) GetUnit() *UnitVO {
	if x != nil {
		return x.Unit
	}
	return nil
}

type UnitGetByURIReq struct {
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
}

func (x *UnitGetByURIReq) Reset() { *x = UnitGetByURIReq{} }

func (x *UnitGetByURIReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitGetByURIReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitGetByURIReq) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type UnitGetByURIResp struct {
	Unit *UnitVO `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
	Code int32   `protobuf:"varint,255,opt,name=code" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,256,opt,name=msg" json:"msg,omitempty"`
}

func (x *UnitGetByURIResp) Reset() { *x = UnitGetByURIResp{} }

func (x *UnitGetByURIResp) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UnitGetByURIResp) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UnitGetByURIResp) GetUnit() *UnitVO {
	if x != nil {
		return x.Unit
	}
	return nil
}

func (x *UnitGetByURIResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnitGetByURIResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateUnitReq struct {
	Unit *UnitVO `protobuf:"bytes,1,opt,name=unit" json:"unit,omitempty"`
}

func (x *CreateUnitReq) Reset() { *x = CreateUnitReq{} }

func (x *CreateUnitReq) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CreateUnitReq) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CreateUnitReq) GetUnit() *UnitVO {
	if x != nil {
		return x.Unit
	}
	return nil
}
