// Code generated by Kitex v0.16.1. DO NOT EDIT.

package dashboard

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	core_api "github.com/xh-polaris/psych-idl/kitex_gen/core_api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	DashboardGetDataOverview(ctx context.Context, Req *core_api.DashboardGetDataOverviewReq, callOptions ...callopt.Option) (r *core_api.DashboardGetDataOverviewResp, err error)
	DashboardGetDataTrend(ctx context.Context, Req *core_api.DashboardGetDataTrendReq, callOptions ...callopt.Option) (r *core_api.DashboardGetDataTrendResp, err error)
	DashboardListUnits(ctx context.Context, Req *core_api.DashboardListUnitsReq, callOptions ...callopt.Option) (r *core_api.DashboardListUnitsResp, err error)
	DashboardGetPsychTrend(ctx context.Context, Req *core_api.DashboardGetPsychTrendReq, callOptions ...callopt.Option) (r *core_api.DashboardGetPsychTrendResp, err error)
	DashboardGetAlarmOverview(ctx context.Context, Req *core_api.DashboardGetAlarmOverviewReq, callOptions ...callopt.Option) (r *core_api.DashboardGetAlarmOverviewResp, err error)
	DashboardListAlarmRecords(ctx context.Context, Req *core_api.DashboardListAlarmRecordsReq, callOptions ...callopt.Option) (r *core_api.DashboardListAlarmRecordsResp, err error)
	DashboardUpdateAlarm(ctx context.Context, Req *core_api.DashboardUpdateAlarmReq, callOptions ...callopt.Option) (r *core_api.DashboardUpdateAlarmResp, err error)
	DashboardListClasses(ctx context.Context, Req *core_api.DashboardListClassesReq, callOptions ...callopt.Option) (r *core_api.DashboardListClassesResp, err error)
	DashboardListUsers(ctx context.Context, Req *core_api.DashboardListUsersReq, callOptions ...callopt.Option) (r *core_api.DashboardListUsersResp, err error)
	DashboardUserConvRecords(ctx context.Context, Req *core_api.DashboardUserConvRecordsReq, callOptions ...callopt.Option) (r *core_api.DashboardUserConvRecordsResp, err error)
	DashboardUnitConvRecords(ctx context.Context, Req *core_api.DashboardUnitConvRecordsReq, callOptions ...callopt.Option) (r *core_api.DashboardUnitConvRecordsResp, err error)
	DashboardGetReport(ctx context.Context, Req *core_api.DashboardGetReportReq, callOptions ...callopt.Option) (r *core_api.DashboardGetReportResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDashboardClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDashboardClient struct {
	*kClient
}

func (p *kDashboardClient) DashboardGetDataOverview(ctx context.Context, Req *core_api.DashboardGetDataOverviewReq, callOptions ...callopt.Option) (r *core_api.DashboardGetDataOverviewResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardGetDataOverview(ctx, Req)
}

func (p *kDashboardClient) DashboardGetDataTrend(ctx context.Context, Req *core_api.DashboardGetDataTrendReq, callOptions ...callopt.Option) (r *core_api.DashboardGetDataTrendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardGetDataTrend(ctx, Req)
}

func (p *kDashboardClient) DashboardListUnits(ctx context.Context, Req *core_api.DashboardListUnitsReq, callOptions ...callopt.Option) (r *core_api.DashboardListUnitsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardListUnits(ctx, Req)
}

func (p *kDashboardClient) DashboardGetPsychTrend(ctx context.Context, Req *core_api.DashboardGetPsychTrendReq, callOptions ...callopt.Option) (r *core_api.DashboardGetPsychTrendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardGetPsychTrend(ctx, Req)
}

func (p *kDashboardClient) DashboardGetAlarmOverview(ctx context.Context, Req *core_api.DashboardGetAlarmOverviewReq, callOptions ...callopt.Option) (r *core_api.DashboardGetAlarmOverviewResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardGetAlarmOverview(ctx, Req)
}

func (p *kDashboardClient) DashboardListAlarmRecords(ctx context.Context, Req *core_api.DashboardListAlarmRecordsReq, callOptions ...callopt.Option) (r *core_api.DashboardListAlarmRecordsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardListAlarmRecords(ctx, Req)
}

func (p *kDashboardClient) DashboardUpdateAlarm(ctx context.Context, Req *core_api.DashboardUpdateAlarmReq, callOptions ...callopt.Option) (r *core_api.DashboardUpdateAlarmResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardUpdateAlarm(ctx, Req)
}

func (p *kDashboardClient) DashboardListClasses(ctx context.Context, Req *core_api.DashboardListClassesReq, callOptions ...callopt.Option) (r *core_api.DashboardListClassesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardListClasses(ctx, Req)
}

func (p *kDashboardClient) DashboardListUsers(ctx context.Context, Req *core_api.DashboardListUsersReq, callOptions ...callopt.Option) (r *core_api.DashboardListUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardListUsers(ctx, Req)
}

func (p *kDashboardClient) DashboardUserConvRecords(ctx context.Context, Req *core_api.DashboardUserConvRecordsReq, callOptions ...callopt.Option) (r *core_api.DashboardUserConvRecordsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardUserConvRecords(ctx, Req)
}

func (p *kDashboardClient) DashboardUnitConvRecords(ctx context.Context, Req *core_api.DashboardUnitConvRecordsReq, callOptions ...callopt.Option) (r *core_api.DashboardUnitConvRecordsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardUnitConvRecords(ctx, Req)
}

func (p *kDashboardClient) DashboardGetReport(ctx context.Context, Req *core_api.DashboardGetReportReq, callOptions ...callopt.Option) (r *core_api.DashboardGetReportResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DashboardGetReport(ctx, Req)
}
