// Code generated by Kitex v0.16.1. DO NOT EDIT.

package dashboard

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	core_api "github.com/xh-polaris/psych-idl/kitex_gen/core_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"DashboardGetDataOverview": kitex.NewMethodInfo(
		dashboardGetDataOverviewHandler,
		newDashboardGetDataOverviewArgs,
		newDashboardGetDataOverviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetDataTrend": kitex.NewMethodInfo(
		dashboardGetDataTrendHandler,
		newDashboardGetDataTrendArgs,
		newDashboardGetDataTrendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListUnits": kitex.NewMethodInfo(
		dashboardListUnitsHandler,
		newDashboardListUnitsArgs,
		newDashboardListUnitsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetPsychTrend": kitex.NewMethodInfo(
		dashboardGetPsychTrendHandler,
		newDashboardGetPsychTrendArgs,
		newDashboardGetPsychTrendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetAlarmOverview": kitex.NewMethodInfo(
		dashboardGetAlarmOverviewHandler,
		newDashboardGetAlarmOverviewArgs,
		newDashboardGetAlarmOverviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListAlarmRecords": kitex.NewMethodInfo(
		dashboardListAlarmRecordsHandler,
		newDashboardListAlarmRecordsArgs,
		newDashboardListAlarmRecordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardUpdateAlarm": kitex.NewMethodInfo(
		dashboardUpdateAlarmHandler,
		newDashboardUpdateAlarmArgs,
		newDashboardUpdateAlarmResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListClasses": kitex.NewMethodInfo(
		dashboardListClassesHandler,
		newDashboardListClassesArgs,
		newDashboardListClassesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListUsers": kitex.NewMethodInfo(
		dashboardListUsersHandler,
		newDashboardListUsersArgs,
		newDashboardListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardUserConvRecords": kitex.NewMethodInfo(
		dashboardUserConvRecordsHandler,
		newDashboardUserConvRecordsArgs,
		newDashboardUserConvRecordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardUnitConvRecords": kitex.NewMethodInfo(
		dashboardUnitConvRecordsHandler,
		newDashboardUnitConvRecordsArgs,
		newDashboardUnitConvRecordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetReport": kitex.NewMethodInfo(
		dashboardGetReportHandler,
		newDashboardGetReportArgs,
		newDashboardGetReportResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardCreateRemark": kitex.NewMethodInfo(
		dashboardCreateRemarkHandler,
		newDashboardCreateRemarkArgs,
		newDashboardCreateRemarkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	dashboardServiceInfo                = NewServiceInfo()
	dashboardServiceInfoForClient       = NewServiceInfoForClient()
	dashboardServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return dashboardServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return dashboardServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return dashboardServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Dashboard"
	handlerType := (*core_api.Dashboard)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "core_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func dashboardGetDataOverviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetDataOverviewReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardGetDataOverview(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetDataOverviewArgs:
		success, err := handler.(core_api.Dashboard).DashboardGetDataOverview(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetDataOverviewResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetDataOverviewArgs() interface{} {
	return &DashboardGetDataOverviewArgs{}
}

func newDashboardGetDataOverviewResult() interface{} {
	return &DashboardGetDataOverviewResult{}
}

type DashboardGetDataOverviewArgs struct {
	Req *core_api.DashboardGetDataOverviewReq
}

func (p *DashboardGetDataOverviewArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetDataOverviewArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataOverviewReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetDataOverviewArgs_Req_DEFAULT *core_api.DashboardGetDataOverviewReq

func (p *DashboardGetDataOverviewArgs) GetReq() *core_api.DashboardGetDataOverviewReq {
	if !p.IsSetReq() {
		return DashboardGetDataOverviewArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetDataOverviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetDataOverviewArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetDataOverviewResult struct {
	Success *core_api.DashboardGetDataOverviewResp
}

var DashboardGetDataOverviewResult_Success_DEFAULT *core_api.DashboardGetDataOverviewResp

func (p *DashboardGetDataOverviewResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetDataOverviewResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataOverviewResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetDataOverviewResult) GetSuccess() *core_api.DashboardGetDataOverviewResp {
	if !p.IsSetSuccess() {
		return DashboardGetDataOverviewResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetDataOverviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetDataOverviewResp)
}

func (p *DashboardGetDataOverviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetDataOverviewResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetDataTrendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetDataTrendReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardGetDataTrend(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetDataTrendArgs:
		success, err := handler.(core_api.Dashboard).DashboardGetDataTrend(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetDataTrendResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetDataTrendArgs() interface{} {
	return &DashboardGetDataTrendArgs{}
}

func newDashboardGetDataTrendResult() interface{} {
	return &DashboardGetDataTrendResult{}
}

type DashboardGetDataTrendArgs struct {
	Req *core_api.DashboardGetDataTrendReq
}

func (p *DashboardGetDataTrendArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetDataTrendArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataTrendReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetDataTrendArgs_Req_DEFAULT *core_api.DashboardGetDataTrendReq

func (p *DashboardGetDataTrendArgs) GetReq() *core_api.DashboardGetDataTrendReq {
	if !p.IsSetReq() {
		return DashboardGetDataTrendArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetDataTrendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetDataTrendArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetDataTrendResult struct {
	Success *core_api.DashboardGetDataTrendResp
}

var DashboardGetDataTrendResult_Success_DEFAULT *core_api.DashboardGetDataTrendResp

func (p *DashboardGetDataTrendResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetDataTrendResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataTrendResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetDataTrendResult) GetSuccess() *core_api.DashboardGetDataTrendResp {
	if !p.IsSetSuccess() {
		return DashboardGetDataTrendResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetDataTrendResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetDataTrendResp)
}

func (p *DashboardGetDataTrendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetDataTrendResult) GetResult() interface{} {
	return p.Success
}

func dashboardListUnitsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListUnitsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardListUnits(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListUnitsArgs:
		success, err := handler.(core_api.Dashboard).DashboardListUnits(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListUnitsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListUnitsArgs() interface{} {
	return &DashboardListUnitsArgs{}
}

func newDashboardListUnitsResult() interface{} {
	return &DashboardListUnitsResult{}
}

type DashboardListUnitsArgs struct {
	Req *core_api.DashboardListUnitsReq
}

func (p *DashboardListUnitsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListUnitsArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUnitsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListUnitsArgs_Req_DEFAULT *core_api.DashboardListUnitsReq

func (p *DashboardListUnitsArgs) GetReq() *core_api.DashboardListUnitsReq {
	if !p.IsSetReq() {
		return DashboardListUnitsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListUnitsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListUnitsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListUnitsResult struct {
	Success *core_api.DashboardListUnitsResp
}

var DashboardListUnitsResult_Success_DEFAULT *core_api.DashboardListUnitsResp

func (p *DashboardListUnitsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListUnitsResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUnitsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListUnitsResult) GetSuccess() *core_api.DashboardListUnitsResp {
	if !p.IsSetSuccess() {
		return DashboardListUnitsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListUnitsResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListUnitsResp)
}

func (p *DashboardListUnitsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListUnitsResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetPsychTrendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetPsychTrendReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardGetPsychTrend(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetPsychTrendArgs:
		success, err := handler.(core_api.Dashboard).DashboardGetPsychTrend(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetPsychTrendResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetPsychTrendArgs() interface{} {
	return &DashboardGetPsychTrendArgs{}
}

func newDashboardGetPsychTrendResult() interface{} {
	return &DashboardGetPsychTrendResult{}
}

type DashboardGetPsychTrendArgs struct {
	Req *core_api.DashboardGetPsychTrendReq
}

func (p *DashboardGetPsychTrendArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetPsychTrendArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetPsychTrendReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetPsychTrendArgs_Req_DEFAULT *core_api.DashboardGetPsychTrendReq

func (p *DashboardGetPsychTrendArgs) GetReq() *core_api.DashboardGetPsychTrendReq {
	if !p.IsSetReq() {
		return DashboardGetPsychTrendArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetPsychTrendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetPsychTrendArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetPsychTrendResult struct {
	Success *core_api.DashboardGetPsychTrendResp
}

var DashboardGetPsychTrendResult_Success_DEFAULT *core_api.DashboardGetPsychTrendResp

func (p *DashboardGetPsychTrendResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetPsychTrendResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetPsychTrendResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetPsychTrendResult) GetSuccess() *core_api.DashboardGetPsychTrendResp {
	if !p.IsSetSuccess() {
		return DashboardGetPsychTrendResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetPsychTrendResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetPsychTrendResp)
}

func (p *DashboardGetPsychTrendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetPsychTrendResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetAlarmOverviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetAlarmOverviewReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardGetAlarmOverview(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetAlarmOverviewArgs:
		success, err := handler.(core_api.Dashboard).DashboardGetAlarmOverview(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetAlarmOverviewResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetAlarmOverviewArgs() interface{} {
	return &DashboardGetAlarmOverviewArgs{}
}

func newDashboardGetAlarmOverviewResult() interface{} {
	return &DashboardGetAlarmOverviewResult{}
}

type DashboardGetAlarmOverviewArgs struct {
	Req *core_api.DashboardGetAlarmOverviewReq
}

func (p *DashboardGetAlarmOverviewArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetAlarmOverviewArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetAlarmOverviewReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetAlarmOverviewArgs_Req_DEFAULT *core_api.DashboardGetAlarmOverviewReq

func (p *DashboardGetAlarmOverviewArgs) GetReq() *core_api.DashboardGetAlarmOverviewReq {
	if !p.IsSetReq() {
		return DashboardGetAlarmOverviewArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetAlarmOverviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetAlarmOverviewArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetAlarmOverviewResult struct {
	Success *core_api.DashboardGetAlarmOverviewResp
}

var DashboardGetAlarmOverviewResult_Success_DEFAULT *core_api.DashboardGetAlarmOverviewResp

func (p *DashboardGetAlarmOverviewResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetAlarmOverviewResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetAlarmOverviewResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetAlarmOverviewResult) GetSuccess() *core_api.DashboardGetAlarmOverviewResp {
	if !p.IsSetSuccess() {
		return DashboardGetAlarmOverviewResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetAlarmOverviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetAlarmOverviewResp)
}

func (p *DashboardGetAlarmOverviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetAlarmOverviewResult) GetResult() interface{} {
	return p.Success
}

func dashboardListAlarmRecordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListAlarmRecordsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardListAlarmRecords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListAlarmRecordsArgs:
		success, err := handler.(core_api.Dashboard).DashboardListAlarmRecords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListAlarmRecordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListAlarmRecordsArgs() interface{} {
	return &DashboardListAlarmRecordsArgs{}
}

func newDashboardListAlarmRecordsResult() interface{} {
	return &DashboardListAlarmRecordsResult{}
}

type DashboardListAlarmRecordsArgs struct {
	Req *core_api.DashboardListAlarmRecordsReq
}

func (p *DashboardListAlarmRecordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListAlarmRecordsArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListAlarmRecordsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListAlarmRecordsArgs_Req_DEFAULT *core_api.DashboardListAlarmRecordsReq

func (p *DashboardListAlarmRecordsArgs) GetReq() *core_api.DashboardListAlarmRecordsReq {
	if !p.IsSetReq() {
		return DashboardListAlarmRecordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListAlarmRecordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListAlarmRecordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListAlarmRecordsResult struct {
	Success *core_api.DashboardListAlarmRecordsResp
}

var DashboardListAlarmRecordsResult_Success_DEFAULT *core_api.DashboardListAlarmRecordsResp

func (p *DashboardListAlarmRecordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListAlarmRecordsResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListAlarmRecordsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListAlarmRecordsResult) GetSuccess() *core_api.DashboardListAlarmRecordsResp {
	if !p.IsSetSuccess() {
		return DashboardListAlarmRecordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListAlarmRecordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListAlarmRecordsResp)
}

func (p *DashboardListAlarmRecordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListAlarmRecordsResult) GetResult() interface{} {
	return p.Success
}

func dashboardUpdateAlarmHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardUpdateAlarmReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardUpdateAlarm(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardUpdateAlarmArgs:
		success, err := handler.(core_api.Dashboard).DashboardUpdateAlarm(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardUpdateAlarmResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardUpdateAlarmArgs() interface{} {
	return &DashboardUpdateAlarmArgs{}
}

func newDashboardUpdateAlarmResult() interface{} {
	return &DashboardUpdateAlarmResult{}
}

type DashboardUpdateAlarmArgs struct {
	Req *core_api.DashboardUpdateAlarmReq
}

func (p *DashboardUpdateAlarmArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardUpdateAlarmArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardUpdateAlarmReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardUpdateAlarmArgs_Req_DEFAULT *core_api.DashboardUpdateAlarmReq

func (p *DashboardUpdateAlarmArgs) GetReq() *core_api.DashboardUpdateAlarmReq {
	if !p.IsSetReq() {
		return DashboardUpdateAlarmArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardUpdateAlarmArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardUpdateAlarmArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardUpdateAlarmResult struct {
	Success *core_api.DashboardUpdateAlarmResp
}

var DashboardUpdateAlarmResult_Success_DEFAULT *core_api.DashboardUpdateAlarmResp

func (p *DashboardUpdateAlarmResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardUpdateAlarmResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardUpdateAlarmResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardUpdateAlarmResult) GetSuccess() *core_api.DashboardUpdateAlarmResp {
	if !p.IsSetSuccess() {
		return DashboardUpdateAlarmResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardUpdateAlarmResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardUpdateAlarmResp)
}

func (p *DashboardUpdateAlarmResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardUpdateAlarmResult) GetResult() interface{} {
	return p.Success
}

func dashboardListClassesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListClassesReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardListClasses(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListClassesArgs:
		success, err := handler.(core_api.Dashboard).DashboardListClasses(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListClassesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListClassesArgs() interface{} {
	return &DashboardListClassesArgs{}
}

func newDashboardListClassesResult() interface{} {
	return &DashboardListClassesResult{}
}

type DashboardListClassesArgs struct {
	Req *core_api.DashboardListClassesReq
}

func (p *DashboardListClassesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListClassesArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListClassesReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListClassesArgs_Req_DEFAULT *core_api.DashboardListClassesReq

func (p *DashboardListClassesArgs) GetReq() *core_api.DashboardListClassesReq {
	if !p.IsSetReq() {
		return DashboardListClassesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListClassesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListClassesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListClassesResult struct {
	Success *core_api.DashboardListClassesResp
}

var DashboardListClassesResult_Success_DEFAULT *core_api.DashboardListClassesResp

func (p *DashboardListClassesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListClassesResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListClassesResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListClassesResult) GetSuccess() *core_api.DashboardListClassesResp {
	if !p.IsSetSuccess() {
		return DashboardListClassesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListClassesResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListClassesResp)
}

func (p *DashboardListClassesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListClassesResult) GetResult() interface{} {
	return p.Success
}

func dashboardListUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListUsersReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardListUsers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListUsersArgs:
		success, err := handler.(core_api.Dashboard).DashboardListUsers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListUsersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListUsersArgs() interface{} {
	return &DashboardListUsersArgs{}
}

func newDashboardListUsersResult() interface{} {
	return &DashboardListUsersResult{}
}

type DashboardListUsersArgs struct {
	Req *core_api.DashboardListUsersReq
}

func (p *DashboardListUsersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListUsersArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUsersReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListUsersArgs_Req_DEFAULT *core_api.DashboardListUsersReq

func (p *DashboardListUsersArgs) GetReq() *core_api.DashboardListUsersReq {
	if !p.IsSetReq() {
		return DashboardListUsersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListUsersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListUsersResult struct {
	Success *core_api.DashboardListUsersResp
}

var DashboardListUsersResult_Success_DEFAULT *core_api.DashboardListUsersResp

func (p *DashboardListUsersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListUsersResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUsersResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListUsersResult) GetSuccess() *core_api.DashboardListUsersResp {
	if !p.IsSetSuccess() {
		return DashboardListUsersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListUsersResp)
}

func (p *DashboardListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListUsersResult) GetResult() interface{} {
	return p.Success
}

func dashboardUserConvRecordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardUserConvRecordsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardUserConvRecords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardUserConvRecordsArgs:
		success, err := handler.(core_api.Dashboard).DashboardUserConvRecords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardUserConvRecordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardUserConvRecordsArgs() interface{} {
	return &DashboardUserConvRecordsArgs{}
}

func newDashboardUserConvRecordsResult() interface{} {
	return &DashboardUserConvRecordsResult{}
}

type DashboardUserConvRecordsArgs struct {
	Req *core_api.DashboardUserConvRecordsReq
}

func (p *DashboardUserConvRecordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardUserConvRecordsArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardUserConvRecordsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardUserConvRecordsArgs_Req_DEFAULT *core_api.DashboardUserConvRecordsReq

func (p *DashboardUserConvRecordsArgs) GetReq() *core_api.DashboardUserConvRecordsReq {
	if !p.IsSetReq() {
		return DashboardUserConvRecordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardUserConvRecordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardUserConvRecordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardUserConvRecordsResult struct {
	Success *core_api.DashboardUserConvRecordsResp
}

var DashboardUserConvRecordsResult_Success_DEFAULT *core_api.DashboardUserConvRecordsResp

func (p *DashboardUserConvRecordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardUserConvRecordsResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardUserConvRecordsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardUserConvRecordsResult) GetSuccess() *core_api.DashboardUserConvRecordsResp {
	if !p.IsSetSuccess() {
		return DashboardUserConvRecordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardUserConvRecordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardUserConvRecordsResp)
}

func (p *DashboardUserConvRecordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardUserConvRecordsResult) GetResult() interface{} {
	return p.Success
}

func dashboardUnitConvRecordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardUnitConvRecordsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardUnitConvRecords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardUnitConvRecordsArgs:
		success, err := handler.(core_api.Dashboard).DashboardUnitConvRecords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardUnitConvRecordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardUnitConvRecordsArgs() interface{} {
	return &DashboardUnitConvRecordsArgs{}
}

func newDashboardUnitConvRecordsResult() interface{} {
	return &DashboardUnitConvRecordsResult{}
}

type DashboardUnitConvRecordsArgs struct {
	Req *core_api.DashboardUnitConvRecordsReq
}

func (p *DashboardUnitConvRecordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardUnitConvRecordsArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardUnitConvRecordsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardUnitConvRecordsArgs_Req_DEFAULT *core_api.DashboardUnitConvRecordsReq

func (p *DashboardUnitConvRecordsArgs) GetReq() *core_api.DashboardUnitConvRecordsReq {
	if !p.IsSetReq() {
		return DashboardUnitConvRecordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardUnitConvRecordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardUnitConvRecordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardUnitConvRecordsResult struct {
	Success *core_api.DashboardUnitConvRecordsResp
}

var DashboardUnitConvRecordsResult_Success_DEFAULT *core_api.DashboardUnitConvRecordsResp

func (p *DashboardUnitConvRecordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardUnitConvRecordsResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardUnitConvRecordsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardUnitConvRecordsResult) GetSuccess() *core_api.DashboardUnitConvRecordsResp {
	if !p.IsSetSuccess() {
		return DashboardUnitConvRecordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardUnitConvRecordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardUnitConvRecordsResp)
}

func (p *DashboardUnitConvRecordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardUnitConvRecordsResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetReportHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetReportReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardGetReport(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetReportArgs:
		success, err := handler.(core_api.Dashboard).DashboardGetReport(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetReportResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetReportArgs() interface{} {
	return &DashboardGetReportArgs{}
}

func newDashboardGetReportResult() interface{} {
	return &DashboardGetReportResult{}
}

type DashboardGetReportArgs struct {
	Req *core_api.DashboardGetReportReq
}

func (p *DashboardGetReportArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetReportArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetReportReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetReportArgs_Req_DEFAULT *core_api.DashboardGetReportReq

func (p *DashboardGetReportArgs) GetReq() *core_api.DashboardGetReportReq {
	if !p.IsSetReq() {
		return DashboardGetReportArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetReportArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetReportArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetReportResult struct {
	Success *core_api.DashboardGetReportResp
}

var DashboardGetReportResult_Success_DEFAULT *core_api.DashboardGetReportResp

func (p *DashboardGetReportResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetReportResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetReportResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetReportResult) GetSuccess() *core_api.DashboardGetReportResp {
	if !p.IsSetSuccess() {
		return DashboardGetReportResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetReportResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetReportResp)
}

func (p *DashboardGetReportResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetReportResult) GetResult() interface{} {
	return p.Success
}

func dashboardCreateRemarkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardCreateRemarkReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Dashboard).DashboardCreateRemark(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardCreateRemarkArgs:
		success, err := handler.(core_api.Dashboard).DashboardCreateRemark(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardCreateRemarkResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardCreateRemarkArgs() interface{} {
	return &DashboardCreateRemarkArgs{}
}

func newDashboardCreateRemarkResult() interface{} {
	return &DashboardCreateRemarkResult{}
}

type DashboardCreateRemarkArgs struct {
	Req *core_api.DashboardCreateRemarkReq
}

func (p *DashboardCreateRemarkArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardCreateRemarkArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardCreateRemarkReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardCreateRemarkArgs_Req_DEFAULT *core_api.DashboardCreateRemarkReq

func (p *DashboardCreateRemarkArgs) GetReq() *core_api.DashboardCreateRemarkReq {
	if !p.IsSetReq() {
		return DashboardCreateRemarkArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardCreateRemarkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardCreateRemarkArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardCreateRemarkResult struct {
	Success *core_api.DashboardCreateRemarkResp
}

var DashboardCreateRemarkResult_Success_DEFAULT *core_api.DashboardCreateRemarkResp

func (p *DashboardCreateRemarkResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardCreateRemarkResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardCreateRemarkResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardCreateRemarkResult) GetSuccess() *core_api.DashboardCreateRemarkResp {
	if !p.IsSetSuccess() {
		return DashboardCreateRemarkResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardCreateRemarkResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardCreateRemarkResp)
}

func (p *DashboardCreateRemarkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardCreateRemarkResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DashboardGetDataOverview(ctx context.Context, Req *core_api.DashboardGetDataOverviewReq) (r *core_api.DashboardGetDataOverviewResp, err error) {
	var _args DashboardGetDataOverviewArgs
	_args.Req = Req
	var _result DashboardGetDataOverviewResult
	if err = p.c.Call(ctx, "DashboardGetDataOverview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetDataTrend(ctx context.Context, Req *core_api.DashboardGetDataTrendReq) (r *core_api.DashboardGetDataTrendResp, err error) {
	var _args DashboardGetDataTrendArgs
	_args.Req = Req
	var _result DashboardGetDataTrendResult
	if err = p.c.Call(ctx, "DashboardGetDataTrend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListUnits(ctx context.Context, Req *core_api.DashboardListUnitsReq) (r *core_api.DashboardListUnitsResp, err error) {
	var _args DashboardListUnitsArgs
	_args.Req = Req
	var _result DashboardListUnitsResult
	if err = p.c.Call(ctx, "DashboardListUnits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetPsychTrend(ctx context.Context, Req *core_api.DashboardGetPsychTrendReq) (r *core_api.DashboardGetPsychTrendResp, err error) {
	var _args DashboardGetPsychTrendArgs
	_args.Req = Req
	var _result DashboardGetPsychTrendResult
	if err = p.c.Call(ctx, "DashboardGetPsychTrend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetAlarmOverview(ctx context.Context, Req *core_api.DashboardGetAlarmOverviewReq) (r *core_api.DashboardGetAlarmOverviewResp, err error) {
	var _args DashboardGetAlarmOverviewArgs
	_args.Req = Req
	var _result DashboardGetAlarmOverviewResult
	if err = p.c.Call(ctx, "DashboardGetAlarmOverview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListAlarmRecords(ctx context.Context, Req *core_api.DashboardListAlarmRecordsReq) (r *core_api.DashboardListAlarmRecordsResp, err error) {
	var _args DashboardListAlarmRecordsArgs
	_args.Req = Req
	var _result DashboardListAlarmRecordsResult
	if err = p.c.Call(ctx, "DashboardListAlarmRecords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardUpdateAlarm(ctx context.Context, Req *core_api.DashboardUpdateAlarmReq) (r *core_api.DashboardUpdateAlarmResp, err error) {
	var _args DashboardUpdateAlarmArgs
	_args.Req = Req
	var _result DashboardUpdateAlarmResult
	if err = p.c.Call(ctx, "DashboardUpdateAlarm", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListClasses(ctx context.Context, Req *core_api.DashboardListClassesReq) (r *core_api.DashboardListClassesResp, err error) {
	var _args DashboardListClassesArgs
	_args.Req = Req
	var _result DashboardListClassesResult
	if err = p.c.Call(ctx, "DashboardListClasses", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListUsers(ctx context.Context, Req *core_api.DashboardListUsersReq) (r *core_api.DashboardListUsersResp, err error) {
	var _args DashboardListUsersArgs
	_args.Req = Req
	var _result DashboardListUsersResult
	if err = p.c.Call(ctx, "DashboardListUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardUserConvRecords(ctx context.Context, Req *core_api.DashboardUserConvRecordsReq) (r *core_api.DashboardUserConvRecordsResp, err error) {
	var _args DashboardUserConvRecordsArgs
	_args.Req = Req
	var _result DashboardUserConvRecordsResult
	if err = p.c.Call(ctx, "DashboardUserConvRecords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardUnitConvRecords(ctx context.Context, Req *core_api.DashboardUnitConvRecordsReq) (r *core_api.DashboardUnitConvRecordsResp, err error) {
	var _args DashboardUnitConvRecordsArgs
	_args.Req = Req
	var _result DashboardUnitConvRecordsResult
	if err = p.c.Call(ctx, "DashboardUnitConvRecords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetReport(ctx context.Context, Req *core_api.DashboardGetReportReq) (r *core_api.DashboardGetReportResp, err error) {
	var _args DashboardGetReportArgs
	_args.Req = Req
	var _result DashboardGetReportResult
	if err = p.c.Call(ctx, "DashboardGetReport", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardCreateRemark(ctx context.Context, Req *core_api.DashboardCreateRemarkReq) (r *core_api.DashboardCreateRemarkResp, err error) {
	var _args DashboardCreateRemarkArgs
	_args.Req = Req
	var _result DashboardCreateRemarkResult
	if err = p.c.Call(ctx, "DashboardCreateRemark", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
