// Code generated by Kitex v0.15.2. DO NOT EDIT.

package psychprofileservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	basic "github.com/xh-polaris/psych-idl/kitex_gen/basic"
	profile "github.com/xh-polaris/psych-idl/kitex_gen/profile"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UserSignUp": kitex.NewMethodInfo(
		userSignUpHandler,
		newUserSignUpArgs,
		newUserSignUpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserSignIn": kitex.NewMethodInfo(
		userSignInHandler,
		newUserSignInArgs,
		newUserSignInResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserGetInfo": kitex.NewMethodInfo(
		userGetInfoHandler,
		newUserGetInfoArgs,
		newUserGetInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserUpdateInfo": kitex.NewMethodInfo(
		userUpdateInfoHandler,
		newUserUpdateInfoArgs,
		newUserUpdateInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserUpdatePassword": kitex.NewMethodInfo(
		userUpdatePasswordHandler,
		newUserUpdatePasswordArgs,
		newUserUpdatePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitSignUp": kitex.NewMethodInfo(
		unitSignUpHandler,
		newUnitSignUpArgs,
		newUnitSignUpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitSignIn": kitex.NewMethodInfo(
		unitSignInHandler,
		newUnitSignInArgs,
		newUnitSignInResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitGetInfo": kitex.NewMethodInfo(
		unitGetInfoHandler,
		newUnitGetInfoArgs,
		newUnitGetInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitUpdateInfo": kitex.NewMethodInfo(
		unitUpdateInfoHandler,
		newUnitUpdateInfoArgs,
		newUnitUpdateInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitUpdatePassword": kitex.NewMethodInfo(
		unitUpdatePasswordHandler,
		newUnitUpdatePasswordArgs,
		newUnitUpdatePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitLinkUser": kitex.NewMethodInfo(
		unitLinkUserHandler,
		newUnitLinkUserArgs,
		newUnitLinkUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitCreateAndLinkUser": kitex.NewMethodInfo(
		unitCreateAndLinkUserHandler,
		newUnitCreateAndLinkUserArgs,
		newUnitCreateAndLinkUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitAppConfigCreateOrUpDate": kitex.NewMethodInfo(
		unitAppConfigCreateOrUpDateHandler,
		newUnitAppConfigCreateOrUpDateArgs,
		newUnitAppConfigCreateOrUpDateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitAppConfigFindByUnitID": kitex.NewMethodInfo(
		unitAppConfigFindByUnitIDHandler,
		newUnitAppConfigFindByUnitIDArgs,
		newUnitAppConfigFindByUnitIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	psychProfileServiceServiceInfo                = NewServiceInfo()
	psychProfileServiceServiceInfoForClient       = NewServiceInfoForClient()
	psychProfileServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return psychProfileServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return psychProfileServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return psychProfileServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PsychProfileService"
	handlerType := (*profile.PsychProfileService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "model",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func userSignUpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UserSignUpReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UserSignUp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserSignUpArgs:
		success, err := handler.(profile.PsychProfileService).UserSignUp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserSignUpResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserSignUpArgs() interface{} {
	return &UserSignUpArgs{}
}

func newUserSignUpResult() interface{} {
	return &UserSignUpResult{}
}

type UserSignUpArgs struct {
	Req *profile.UserSignUpReq
}

func (p *UserSignUpArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserSignUpArgs) Unmarshal(in []byte) error {
	msg := new(profile.UserSignUpReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserSignUpArgs_Req_DEFAULT *profile.UserSignUpReq

func (p *UserSignUpArgs) GetReq() *profile.UserSignUpReq {
	if !p.IsSetReq() {
		return UserSignUpArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserSignUpArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSignUpArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserSignUpResult struct {
	Success *profile.UserSignUpResp
}

var UserSignUpResult_Success_DEFAULT *profile.UserSignUpResp

func (p *UserSignUpResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserSignUpResult) Unmarshal(in []byte) error {
	msg := new(profile.UserSignUpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserSignUpResult) GetSuccess() *profile.UserSignUpResp {
	if !p.IsSetSuccess() {
		return UserSignUpResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserSignUpResult) SetSuccess(x interface{}) {
	p.Success = x.(*profile.UserSignUpResp)
}

func (p *UserSignUpResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSignUpResult) GetResult() interface{} {
	return p.Success
}

func userSignInHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UserSignInReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UserSignIn(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserSignInArgs:
		success, err := handler.(profile.PsychProfileService).UserSignIn(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserSignInResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserSignInArgs() interface{} {
	return &UserSignInArgs{}
}

func newUserSignInResult() interface{} {
	return &UserSignInResult{}
}

type UserSignInArgs struct {
	Req *profile.UserSignInReq
}

func (p *UserSignInArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserSignInArgs) Unmarshal(in []byte) error {
	msg := new(profile.UserSignInReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserSignInArgs_Req_DEFAULT *profile.UserSignInReq

func (p *UserSignInArgs) GetReq() *profile.UserSignInReq {
	if !p.IsSetReq() {
		return UserSignInArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserSignInArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSignInArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserSignInResult struct {
	Success *profile.UserSignInResp
}

var UserSignInResult_Success_DEFAULT *profile.UserSignInResp

func (p *UserSignInResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserSignInResult) Unmarshal(in []byte) error {
	msg := new(profile.UserSignInResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserSignInResult) GetSuccess() *profile.UserSignInResp {
	if !p.IsSetSuccess() {
		return UserSignInResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserSignInResult) SetSuccess(x interface{}) {
	p.Success = x.(*profile.UserSignInResp)
}

func (p *UserSignInResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSignInResult) GetResult() interface{} {
	return p.Success
}

func userGetInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UserGetInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UserGetInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserGetInfoArgs:
		success, err := handler.(profile.PsychProfileService).UserGetInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserGetInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserGetInfoArgs() interface{} {
	return &UserGetInfoArgs{}
}

func newUserGetInfoResult() interface{} {
	return &UserGetInfoResult{}
}

type UserGetInfoArgs struct {
	Req *profile.UserGetInfoReq
}

func (p *UserGetInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserGetInfoArgs) Unmarshal(in []byte) error {
	msg := new(profile.UserGetInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserGetInfoArgs_Req_DEFAULT *profile.UserGetInfoReq

func (p *UserGetInfoArgs) GetReq() *profile.UserGetInfoReq {
	if !p.IsSetReq() {
		return UserGetInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserGetInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserGetInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserGetInfoResult struct {
	Success *profile.UserGetInfoResp
}

var UserGetInfoResult_Success_DEFAULT *profile.UserGetInfoResp

func (p *UserGetInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserGetInfoResult) Unmarshal(in []byte) error {
	msg := new(profile.UserGetInfoResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserGetInfoResult) GetSuccess() *profile.UserGetInfoResp {
	if !p.IsSetSuccess() {
		return UserGetInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserGetInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*profile.UserGetInfoResp)
}

func (p *UserGetInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserGetInfoResult) GetResult() interface{} {
	return p.Success
}

func userUpdateInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UserUpdateInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UserUpdateInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserUpdateInfoArgs:
		success, err := handler.(profile.PsychProfileService).UserUpdateInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserUpdateInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserUpdateInfoArgs() interface{} {
	return &UserUpdateInfoArgs{}
}

func newUserUpdateInfoResult() interface{} {
	return &UserUpdateInfoResult{}
}

type UserUpdateInfoArgs struct {
	Req *profile.UserUpdateInfoReq
}

func (p *UserUpdateInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserUpdateInfoArgs) Unmarshal(in []byte) error {
	msg := new(profile.UserUpdateInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserUpdateInfoArgs_Req_DEFAULT *profile.UserUpdateInfoReq

func (p *UserUpdateInfoArgs) GetReq() *profile.UserUpdateInfoReq {
	if !p.IsSetReq() {
		return UserUpdateInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserUpdateInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserUpdateInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserUpdateInfoResult struct {
	Success *basic.Response
}

var UserUpdateInfoResult_Success_DEFAULT *basic.Response

func (p *UserUpdateInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserUpdateInfoResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserUpdateInfoResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UserUpdateInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserUpdateInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UserUpdateInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserUpdateInfoResult) GetResult() interface{} {
	return p.Success
}

func userUpdatePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UserUpdatePasswordReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UserUpdatePassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserUpdatePasswordArgs:
		success, err := handler.(profile.PsychProfileService).UserUpdatePassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserUpdatePasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserUpdatePasswordArgs() interface{} {
	return &UserUpdatePasswordArgs{}
}

func newUserUpdatePasswordResult() interface{} {
	return &UserUpdatePasswordResult{}
}

type UserUpdatePasswordArgs struct {
	Req *profile.UserUpdatePasswordReq
}

func (p *UserUpdatePasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserUpdatePasswordArgs) Unmarshal(in []byte) error {
	msg := new(profile.UserUpdatePasswordReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserUpdatePasswordArgs_Req_DEFAULT *profile.UserUpdatePasswordReq

func (p *UserUpdatePasswordArgs) GetReq() *profile.UserUpdatePasswordReq {
	if !p.IsSetReq() {
		return UserUpdatePasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserUpdatePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserUpdatePasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserUpdatePasswordResult struct {
	Success *basic.Response
}

var UserUpdatePasswordResult_Success_DEFAULT *basic.Response

func (p *UserUpdatePasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserUpdatePasswordResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserUpdatePasswordResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UserUpdatePasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserUpdatePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UserUpdatePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserUpdatePasswordResult) GetResult() interface{} {
	return p.Success
}

func unitSignUpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitSignUpReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitSignUp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitSignUpArgs:
		success, err := handler.(profile.PsychProfileService).UnitSignUp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitSignUpResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitSignUpArgs() interface{} {
	return &UnitSignUpArgs{}
}

func newUnitSignUpResult() interface{} {
	return &UnitSignUpResult{}
}

type UnitSignUpArgs struct {
	Req *profile.UnitSignUpReq
}

func (p *UnitSignUpArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitSignUpArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitSignUpReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitSignUpArgs_Req_DEFAULT *profile.UnitSignUpReq

func (p *UnitSignUpArgs) GetReq() *profile.UnitSignUpReq {
	if !p.IsSetReq() {
		return UnitSignUpArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitSignUpArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitSignUpArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitSignUpResult struct {
	Success *profile.UnitSignUpResp
}

var UnitSignUpResult_Success_DEFAULT *profile.UnitSignUpResp

func (p *UnitSignUpResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitSignUpResult) Unmarshal(in []byte) error {
	msg := new(profile.UnitSignUpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitSignUpResult) GetSuccess() *profile.UnitSignUpResp {
	if !p.IsSetSuccess() {
		return UnitSignUpResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitSignUpResult) SetSuccess(x interface{}) {
	p.Success = x.(*profile.UnitSignUpResp)
}

func (p *UnitSignUpResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitSignUpResult) GetResult() interface{} {
	return p.Success
}

func unitSignInHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitSignInReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitSignIn(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitSignInArgs:
		success, err := handler.(profile.PsychProfileService).UnitSignIn(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitSignInResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitSignInArgs() interface{} {
	return &UnitSignInArgs{}
}

func newUnitSignInResult() interface{} {
	return &UnitSignInResult{}
}

type UnitSignInArgs struct {
	Req *profile.UnitSignInReq
}

func (p *UnitSignInArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitSignInArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitSignInReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitSignInArgs_Req_DEFAULT *profile.UnitSignInReq

func (p *UnitSignInArgs) GetReq() *profile.UnitSignInReq {
	if !p.IsSetReq() {
		return UnitSignInArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitSignInArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitSignInArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitSignInResult struct {
	Success *profile.UnitSignInResp
}

var UnitSignInResult_Success_DEFAULT *profile.UnitSignInResp

func (p *UnitSignInResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitSignInResult) Unmarshal(in []byte) error {
	msg := new(profile.UnitSignInResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitSignInResult) GetSuccess() *profile.UnitSignInResp {
	if !p.IsSetSuccess() {
		return UnitSignInResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitSignInResult) SetSuccess(x interface{}) {
	p.Success = x.(*profile.UnitSignInResp)
}

func (p *UnitSignInResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitSignInResult) GetResult() interface{} {
	return p.Success
}

func unitGetInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitGetInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitGetInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitGetInfoArgs:
		success, err := handler.(profile.PsychProfileService).UnitGetInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitGetInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitGetInfoArgs() interface{} {
	return &UnitGetInfoArgs{}
}

func newUnitGetInfoResult() interface{} {
	return &UnitGetInfoResult{}
}

type UnitGetInfoArgs struct {
	Req *profile.UnitGetInfoReq
}

func (p *UnitGetInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitGetInfoArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitGetInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitGetInfoArgs_Req_DEFAULT *profile.UnitGetInfoReq

func (p *UnitGetInfoArgs) GetReq() *profile.UnitGetInfoReq {
	if !p.IsSetReq() {
		return UnitGetInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitGetInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitGetInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitGetInfoResult struct {
	Success *profile.UnitGetInfoResp
}

var UnitGetInfoResult_Success_DEFAULT *profile.UnitGetInfoResp

func (p *UnitGetInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitGetInfoResult) Unmarshal(in []byte) error {
	msg := new(profile.UnitGetInfoResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitGetInfoResult) GetSuccess() *profile.UnitGetInfoResp {
	if !p.IsSetSuccess() {
		return UnitGetInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitGetInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*profile.UnitGetInfoResp)
}

func (p *UnitGetInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitGetInfoResult) GetResult() interface{} {
	return p.Success
}

func unitUpdateInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitUpdateInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitUpdateInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitUpdateInfoArgs:
		success, err := handler.(profile.PsychProfileService).UnitUpdateInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitUpdateInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitUpdateInfoArgs() interface{} {
	return &UnitUpdateInfoArgs{}
}

func newUnitUpdateInfoResult() interface{} {
	return &UnitUpdateInfoResult{}
}

type UnitUpdateInfoArgs struct {
	Req *profile.UnitUpdateInfoReq
}

func (p *UnitUpdateInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitUpdateInfoArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitUpdateInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitUpdateInfoArgs_Req_DEFAULT *profile.UnitUpdateInfoReq

func (p *UnitUpdateInfoArgs) GetReq() *profile.UnitUpdateInfoReq {
	if !p.IsSetReq() {
		return UnitUpdateInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitUpdateInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitUpdateInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitUpdateInfoResult struct {
	Success *basic.Response
}

var UnitUpdateInfoResult_Success_DEFAULT *basic.Response

func (p *UnitUpdateInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitUpdateInfoResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitUpdateInfoResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UnitUpdateInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitUpdateInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UnitUpdateInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitUpdateInfoResult) GetResult() interface{} {
	return p.Success
}

func unitUpdatePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitUpdatePasswordReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitUpdatePassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitUpdatePasswordArgs:
		success, err := handler.(profile.PsychProfileService).UnitUpdatePassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitUpdatePasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitUpdatePasswordArgs() interface{} {
	return &UnitUpdatePasswordArgs{}
}

func newUnitUpdatePasswordResult() interface{} {
	return &UnitUpdatePasswordResult{}
}

type UnitUpdatePasswordArgs struct {
	Req *profile.UnitUpdatePasswordReq
}

func (p *UnitUpdatePasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitUpdatePasswordArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitUpdatePasswordReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitUpdatePasswordArgs_Req_DEFAULT *profile.UnitUpdatePasswordReq

func (p *UnitUpdatePasswordArgs) GetReq() *profile.UnitUpdatePasswordReq {
	if !p.IsSetReq() {
		return UnitUpdatePasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitUpdatePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitUpdatePasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitUpdatePasswordResult struct {
	Success *basic.Response
}

var UnitUpdatePasswordResult_Success_DEFAULT *basic.Response

func (p *UnitUpdatePasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitUpdatePasswordResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitUpdatePasswordResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UnitUpdatePasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitUpdatePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UnitUpdatePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitUpdatePasswordResult) GetResult() interface{} {
	return p.Success
}

func unitLinkUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitLinkUserReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitLinkUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitLinkUserArgs:
		success, err := handler.(profile.PsychProfileService).UnitLinkUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitLinkUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitLinkUserArgs() interface{} {
	return &UnitLinkUserArgs{}
}

func newUnitLinkUserResult() interface{} {
	return &UnitLinkUserResult{}
}

type UnitLinkUserArgs struct {
	Req *profile.UnitLinkUserReq
}

func (p *UnitLinkUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitLinkUserArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitLinkUserReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitLinkUserArgs_Req_DEFAULT *profile.UnitLinkUserReq

func (p *UnitLinkUserArgs) GetReq() *profile.UnitLinkUserReq {
	if !p.IsSetReq() {
		return UnitLinkUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitLinkUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitLinkUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitLinkUserResult struct {
	Success *basic.Response
}

var UnitLinkUserResult_Success_DEFAULT *basic.Response

func (p *UnitLinkUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitLinkUserResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitLinkUserResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UnitLinkUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitLinkUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UnitLinkUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitLinkUserResult) GetResult() interface{} {
	return p.Success
}

func unitCreateAndLinkUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitCreateAndLinkUserReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitCreateAndLinkUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitCreateAndLinkUserArgs:
		success, err := handler.(profile.PsychProfileService).UnitCreateAndLinkUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitCreateAndLinkUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitCreateAndLinkUserArgs() interface{} {
	return &UnitCreateAndLinkUserArgs{}
}

func newUnitCreateAndLinkUserResult() interface{} {
	return &UnitCreateAndLinkUserResult{}
}

type UnitCreateAndLinkUserArgs struct {
	Req *profile.UnitCreateAndLinkUserReq
}

func (p *UnitCreateAndLinkUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitCreateAndLinkUserArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitCreateAndLinkUserReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitCreateAndLinkUserArgs_Req_DEFAULT *profile.UnitCreateAndLinkUserReq

func (p *UnitCreateAndLinkUserArgs) GetReq() *profile.UnitCreateAndLinkUserReq {
	if !p.IsSetReq() {
		return UnitCreateAndLinkUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitCreateAndLinkUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitCreateAndLinkUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitCreateAndLinkUserResult struct {
	Success *basic.Response
}

var UnitCreateAndLinkUserResult_Success_DEFAULT *basic.Response

func (p *UnitCreateAndLinkUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitCreateAndLinkUserResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitCreateAndLinkUserResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UnitCreateAndLinkUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitCreateAndLinkUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UnitCreateAndLinkUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitCreateAndLinkUserResult) GetResult() interface{} {
	return p.Success
}

func unitAppConfigCreateOrUpDateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitAppConfigCreateOrUpdateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitAppConfigCreateOrUpDate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitAppConfigCreateOrUpDateArgs:
		success, err := handler.(profile.PsychProfileService).UnitAppConfigCreateOrUpDate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitAppConfigCreateOrUpDateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitAppConfigCreateOrUpDateArgs() interface{} {
	return &UnitAppConfigCreateOrUpDateArgs{}
}

func newUnitAppConfigCreateOrUpDateResult() interface{} {
	return &UnitAppConfigCreateOrUpDateResult{}
}

type UnitAppConfigCreateOrUpDateArgs struct {
	Req *profile.UnitAppConfigCreateOrUpdateReq
}

func (p *UnitAppConfigCreateOrUpDateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitAppConfigCreateOrUpDateArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitAppConfigCreateOrUpdateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitAppConfigCreateOrUpDateArgs_Req_DEFAULT *profile.UnitAppConfigCreateOrUpdateReq

func (p *UnitAppConfigCreateOrUpDateArgs) GetReq() *profile.UnitAppConfigCreateOrUpdateReq {
	if !p.IsSetReq() {
		return UnitAppConfigCreateOrUpDateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitAppConfigCreateOrUpDateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitAppConfigCreateOrUpDateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitAppConfigCreateOrUpDateResult struct {
	Success *basic.Response
}

var UnitAppConfigCreateOrUpDateResult_Success_DEFAULT *basic.Response

func (p *UnitAppConfigCreateOrUpDateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitAppConfigCreateOrUpDateResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitAppConfigCreateOrUpDateResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UnitAppConfigCreateOrUpDateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitAppConfigCreateOrUpDateResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UnitAppConfigCreateOrUpDateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitAppConfigCreateOrUpDateResult) GetResult() interface{} {
	return p.Success
}

func unitAppConfigFindByUnitIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(profile.UnitAppConfigGetByUnitIdReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(profile.PsychProfileService).UnitAppConfigFindByUnitID(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitAppConfigFindByUnitIDArgs:
		success, err := handler.(profile.PsychProfileService).UnitAppConfigFindByUnitID(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitAppConfigFindByUnitIDResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitAppConfigFindByUnitIDArgs() interface{} {
	return &UnitAppConfigFindByUnitIDArgs{}
}

func newUnitAppConfigFindByUnitIDResult() interface{} {
	return &UnitAppConfigFindByUnitIDResult{}
}

type UnitAppConfigFindByUnitIDArgs struct {
	Req *profile.UnitAppConfigGetByUnitIdReq
}

func (p *UnitAppConfigFindByUnitIDArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitAppConfigFindByUnitIDArgs) Unmarshal(in []byte) error {
	msg := new(profile.UnitAppConfigGetByUnitIdReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitAppConfigFindByUnitIDArgs_Req_DEFAULT *profile.UnitAppConfigGetByUnitIdReq

func (p *UnitAppConfigFindByUnitIDArgs) GetReq() *profile.UnitAppConfigGetByUnitIdReq {
	if !p.IsSetReq() {
		return UnitAppConfigFindByUnitIDArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitAppConfigFindByUnitIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitAppConfigFindByUnitIDArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitAppConfigFindByUnitIDResult struct {
	Success *profile.UnitAppConfigGetByUnitIdResp
}

var UnitAppConfigFindByUnitIDResult_Success_DEFAULT *profile.UnitAppConfigGetByUnitIdResp

func (p *UnitAppConfigFindByUnitIDResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitAppConfigFindByUnitIDResult) Unmarshal(in []byte) error {
	msg := new(profile.UnitAppConfigGetByUnitIdResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitAppConfigFindByUnitIDResult) GetSuccess() *profile.UnitAppConfigGetByUnitIdResp {
	if !p.IsSetSuccess() {
		return UnitAppConfigFindByUnitIDResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitAppConfigFindByUnitIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*profile.UnitAppConfigGetByUnitIdResp)
}

func (p *UnitAppConfigFindByUnitIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitAppConfigFindByUnitIDResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UserSignUp(ctx context.Context, Req *profile.UserSignUpReq) (r *profile.UserSignUpResp, err error) {
	var _args UserSignUpArgs
	_args.Req = Req
	var _result UserSignUpResult
	if err = p.c.Call(ctx, "UserSignUp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserSignIn(ctx context.Context, Req *profile.UserSignInReq) (r *profile.UserSignInResp, err error) {
	var _args UserSignInArgs
	_args.Req = Req
	var _result UserSignInResult
	if err = p.c.Call(ctx, "UserSignIn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserGetInfo(ctx context.Context, Req *profile.UserGetInfoReq) (r *profile.UserGetInfoResp, err error) {
	var _args UserGetInfoArgs
	_args.Req = Req
	var _result UserGetInfoResult
	if err = p.c.Call(ctx, "UserGetInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserUpdateInfo(ctx context.Context, Req *profile.UserUpdateInfoReq) (r *basic.Response, err error) {
	var _args UserUpdateInfoArgs
	_args.Req = Req
	var _result UserUpdateInfoResult
	if err = p.c.Call(ctx, "UserUpdateInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserUpdatePassword(ctx context.Context, Req *profile.UserUpdatePasswordReq) (r *basic.Response, err error) {
	var _args UserUpdatePasswordArgs
	_args.Req = Req
	var _result UserUpdatePasswordResult
	if err = p.c.Call(ctx, "UserUpdatePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitSignUp(ctx context.Context, Req *profile.UnitSignUpReq) (r *profile.UnitSignUpResp, err error) {
	var _args UnitSignUpArgs
	_args.Req = Req
	var _result UnitSignUpResult
	if err = p.c.Call(ctx, "UnitSignUp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitSignIn(ctx context.Context, Req *profile.UnitSignInReq) (r *profile.UnitSignInResp, err error) {
	var _args UnitSignInArgs
	_args.Req = Req
	var _result UnitSignInResult
	if err = p.c.Call(ctx, "UnitSignIn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitGetInfo(ctx context.Context, Req *profile.UnitGetInfoReq) (r *profile.UnitGetInfoResp, err error) {
	var _args UnitGetInfoArgs
	_args.Req = Req
	var _result UnitGetInfoResult
	if err = p.c.Call(ctx, "UnitGetInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitUpdateInfo(ctx context.Context, Req *profile.UnitUpdateInfoReq) (r *basic.Response, err error) {
	var _args UnitUpdateInfoArgs
	_args.Req = Req
	var _result UnitUpdateInfoResult
	if err = p.c.Call(ctx, "UnitUpdateInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitUpdatePassword(ctx context.Context, Req *profile.UnitUpdatePasswordReq) (r *basic.Response, err error) {
	var _args UnitUpdatePasswordArgs
	_args.Req = Req
	var _result UnitUpdatePasswordResult
	if err = p.c.Call(ctx, "UnitUpdatePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitLinkUser(ctx context.Context, Req *profile.UnitLinkUserReq) (r *basic.Response, err error) {
	var _args UnitLinkUserArgs
	_args.Req = Req
	var _result UnitLinkUserResult
	if err = p.c.Call(ctx, "UnitLinkUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitCreateAndLinkUser(ctx context.Context, Req *profile.UnitCreateAndLinkUserReq) (r *basic.Response, err error) {
	var _args UnitCreateAndLinkUserArgs
	_args.Req = Req
	var _result UnitCreateAndLinkUserResult
	if err = p.c.Call(ctx, "UnitCreateAndLinkUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitAppConfigCreateOrUpDate(ctx context.Context, Req *profile.UnitAppConfigCreateOrUpdateReq) (r *basic.Response, err error) {
	var _args UnitAppConfigCreateOrUpDateArgs
	_args.Req = Req
	var _result UnitAppConfigCreateOrUpDateResult
	if err = p.c.Call(ctx, "UnitAppConfigCreateOrUpDate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitAppConfigFindByUnitID(ctx context.Context, Req *profile.UnitAppConfigGetByUnitIdReq) (r *profile.UnitAppConfigGetByUnitIdResp, err error) {
	var _args UnitAppConfigFindByUnitIDArgs
	_args.Req = Req
	var _result UnitAppConfigFindByUnitIDResult
	if err = p.c.Call(ctx, "UnitAppConfigFindByUnitID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
