// Code generated by Kitex v0.16.3. DO NOT EDIT.

package openapi

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	core_api "github.com/xh-polaris/psych-idl/kitex_gen/core_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"OpenApiChatCompletion": kitex.NewMethodInfo(
		openApiChatCompletionHandler,
		newOpenApiChatCompletionArgs,
		newOpenApiChatCompletionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"OpenApiGenerateReport": kitex.NewMethodInfo(
		openApiGenerateReportHandler,
		newOpenApiGenerateReportArgs,
		newOpenApiGenerateReportResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	openAPIServiceInfo                = NewServiceInfo()
	openAPIServiceInfoForClient       = NewServiceInfoForClient()
	openAPIServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return openAPIServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return openAPIServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return openAPIServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OpenAPI"
	handlerType := (*core_api.OpenAPI)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "core_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func openApiChatCompletionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.OpenApiChatCompletionReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.OpenAPI).OpenApiChatCompletion(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *OpenApiChatCompletionArgs:
		success, err := handler.(core_api.OpenAPI).OpenApiChatCompletion(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*OpenApiChatCompletionResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newOpenApiChatCompletionArgs() interface{} {
	return &OpenApiChatCompletionArgs{}
}

func newOpenApiChatCompletionResult() interface{} {
	return &OpenApiChatCompletionResult{}
}

type OpenApiChatCompletionArgs struct {
	Req *core_api.OpenApiChatCompletionReq
}

func (p *OpenApiChatCompletionArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *OpenApiChatCompletionArgs) Unmarshal(in []byte) error {
	msg := new(core_api.OpenApiChatCompletionReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var OpenApiChatCompletionArgs_Req_DEFAULT *core_api.OpenApiChatCompletionReq

func (p *OpenApiChatCompletionArgs) GetReq() *core_api.OpenApiChatCompletionReq {
	if !p.IsSetReq() {
		return OpenApiChatCompletionArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *OpenApiChatCompletionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OpenApiChatCompletionArgs) GetFirstArgument() interface{} {
	return p.Req
}

type OpenApiChatCompletionResult struct {
	Success *core_api.OpenApiChatCompletionResp
}

var OpenApiChatCompletionResult_Success_DEFAULT *core_api.OpenApiChatCompletionResp

func (p *OpenApiChatCompletionResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *OpenApiChatCompletionResult) Unmarshal(in []byte) error {
	msg := new(core_api.OpenApiChatCompletionResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *OpenApiChatCompletionResult) GetSuccess() *core_api.OpenApiChatCompletionResp {
	if !p.IsSetSuccess() {
		return OpenApiChatCompletionResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OpenApiChatCompletionResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.OpenApiChatCompletionResp)
}

func (p *OpenApiChatCompletionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OpenApiChatCompletionResult) GetResult() interface{} {
	return p.Success
}

func openApiGenerateReportHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.OpenApiGenerateReportReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.OpenAPI).OpenApiGenerateReport(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *OpenApiGenerateReportArgs:
		success, err := handler.(core_api.OpenAPI).OpenApiGenerateReport(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*OpenApiGenerateReportResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newOpenApiGenerateReportArgs() interface{} {
	return &OpenApiGenerateReportArgs{}
}

func newOpenApiGenerateReportResult() interface{} {
	return &OpenApiGenerateReportResult{}
}

type OpenApiGenerateReportArgs struct {
	Req *core_api.OpenApiGenerateReportReq
}

func (p *OpenApiGenerateReportArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *OpenApiGenerateReportArgs) Unmarshal(in []byte) error {
	msg := new(core_api.OpenApiGenerateReportReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var OpenApiGenerateReportArgs_Req_DEFAULT *core_api.OpenApiGenerateReportReq

func (p *OpenApiGenerateReportArgs) GetReq() *core_api.OpenApiGenerateReportReq {
	if !p.IsSetReq() {
		return OpenApiGenerateReportArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *OpenApiGenerateReportArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OpenApiGenerateReportArgs) GetFirstArgument() interface{} {
	return p.Req
}

type OpenApiGenerateReportResult struct {
	Success *core_api.OpenApiGenerateReportResp
}

var OpenApiGenerateReportResult_Success_DEFAULT *core_api.OpenApiGenerateReportResp

func (p *OpenApiGenerateReportResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *OpenApiGenerateReportResult) Unmarshal(in []byte) error {
	msg := new(core_api.OpenApiGenerateReportResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *OpenApiGenerateReportResult) GetSuccess() *core_api.OpenApiGenerateReportResp {
	if !p.IsSetSuccess() {
		return OpenApiGenerateReportResult_Success_DEFAULT
	}
	return p.Success
}

func (p *OpenApiGenerateReportResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.OpenApiGenerateReportResp)
}

func (p *OpenApiGenerateReportResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OpenApiGenerateReportResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) OpenApiChatCompletion(ctx context.Context, Req *core_api.OpenApiChatCompletionReq) (r *core_api.OpenApiChatCompletionResp, err error) {
	var _args OpenApiChatCompletionArgs
	_args.Req = Req
	var _result OpenApiChatCompletionResult
	if err = p.c.Call(ctx, "OpenApiChatCompletion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OpenApiGenerateReport(ctx context.Context, Req *core_api.OpenApiGenerateReportReq) (r *core_api.OpenApiGenerateReportResp, err error) {
	var _args OpenApiGenerateReportArgs
	_args.Req = Req
	var _result OpenApiGenerateReportResult
	if err = p.c.Call(ctx, "OpenApiGenerateReport", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
