// Code generated by Kitex v0.16.3. DO NOT EDIT.

package config

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	basic "github.com/xh-polaris/psych-idl/kitex_gen/basic"
	core_api "github.com/xh-polaris/psych-idl/kitex_gen/core_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ConfigCreate": kitex.NewMethodInfo(
		configCreateHandler,
		newConfigCreateArgs,
		newConfigCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigUpdateInfo": kitex.NewMethodInfo(
		configUpdateInfoHandler,
		newConfigUpdateInfoArgs,
		newConfigUpdateInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigGetByUnitID": kitex.NewMethodInfo(
		configGetByUnitIDHandler,
		newConfigGetByUnitIDArgs,
		newConfigGetByUnitIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigGetCharacter": kitex.NewMethodInfo(
		configGetCharacterHandler,
		newConfigGetCharacterArgs,
		newConfigGetCharacterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigListVoice": kitex.NewMethodInfo(
		configListVoiceHandler,
		newConfigListVoiceArgs,
		newConfigListVoiceResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigAddCharacter": kitex.NewMethodInfo(
		configAddCharacterHandler,
		newConfigAddCharacterArgs,
		newConfigAddCharacterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigUpdateCharacter": kitex.NewMethodInfo(
		configUpdateCharacterHandler,
		newConfigUpdateCharacterArgs,
		newConfigUpdateCharacterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigDeleteCharacter": kitex.NewMethodInfo(
		configDeleteCharacterHandler,
		newConfigDeleteCharacterArgs,
		newConfigDeleteCharacterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	configServiceInfo                = NewServiceInfo()
	configServiceInfoForClient       = NewServiceInfoForClient()
	configServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return configServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return configServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return configServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Config"
	handlerType := (*core_api.Config)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "core_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func configCreateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigCreateOrUpdateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Config).ConfigCreate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigCreateArgs:
		success, err := handler.(core_api.Config).ConfigCreate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigCreateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigCreateArgs() interface{} {
	return &ConfigCreateArgs{}
}

func newConfigCreateResult() interface{} {
	return &ConfigCreateResult{}
}

type ConfigCreateArgs struct {
	Req *core_api.ConfigCreateOrUpdateReq
}

func (p *ConfigCreateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigCreateArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigCreateOrUpdateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigCreateArgs_Req_DEFAULT *core_api.ConfigCreateOrUpdateReq

func (p *ConfigCreateArgs) GetReq() *core_api.ConfigCreateOrUpdateReq {
	if !p.IsSetReq() {
		return ConfigCreateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigCreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigCreateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigCreateResult struct {
	Success *basic.Response
}

var ConfigCreateResult_Success_DEFAULT *basic.Response

func (p *ConfigCreateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigCreateResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigCreateResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return ConfigCreateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigCreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *ConfigCreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigCreateResult) GetResult() interface{} {
	return p.Success
}

func configUpdateInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigCreateOrUpdateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Config).ConfigUpdateInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigUpdateInfoArgs:
		success, err := handler.(core_api.Config).ConfigUpdateInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigUpdateInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigUpdateInfoArgs() interface{} {
	return &ConfigUpdateInfoArgs{}
}

func newConfigUpdateInfoResult() interface{} {
	return &ConfigUpdateInfoResult{}
}

type ConfigUpdateInfoArgs struct {
	Req *core_api.ConfigCreateOrUpdateReq
}

func (p *ConfigUpdateInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigUpdateInfoArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigCreateOrUpdateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigUpdateInfoArgs_Req_DEFAULT *core_api.ConfigCreateOrUpdateReq

func (p *ConfigUpdateInfoArgs) GetReq() *core_api.ConfigCreateOrUpdateReq {
	if !p.IsSetReq() {
		return ConfigUpdateInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigUpdateInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigUpdateInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigUpdateInfoResult struct {
	Success *basic.Response
}

var ConfigUpdateInfoResult_Success_DEFAULT *basic.Response

func (p *ConfigUpdateInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigUpdateInfoResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigUpdateInfoResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return ConfigUpdateInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigUpdateInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *ConfigUpdateInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigUpdateInfoResult) GetResult() interface{} {
	return p.Success
}

func configGetByUnitIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigGetByUnitIdReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Config).ConfigGetByUnitID(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigGetByUnitIDArgs:
		success, err := handler.(core_api.Config).ConfigGetByUnitID(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigGetByUnitIDResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigGetByUnitIDArgs() interface{} {
	return &ConfigGetByUnitIDArgs{}
}

func newConfigGetByUnitIDResult() interface{} {
	return &ConfigGetByUnitIDResult{}
}

type ConfigGetByUnitIDArgs struct {
	Req *core_api.ConfigGetByUnitIdReq
}

func (p *ConfigGetByUnitIDArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigGetByUnitIDArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigGetByUnitIdReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigGetByUnitIDArgs_Req_DEFAULT *core_api.ConfigGetByUnitIdReq

func (p *ConfigGetByUnitIDArgs) GetReq() *core_api.ConfigGetByUnitIdReq {
	if !p.IsSetReq() {
		return ConfigGetByUnitIDArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigGetByUnitIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigGetByUnitIDArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigGetByUnitIDResult struct {
	Success *core_api.ConfigGetByUnitIdResp
}

var ConfigGetByUnitIDResult_Success_DEFAULT *core_api.ConfigGetByUnitIdResp

func (p *ConfigGetByUnitIDResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigGetByUnitIDResult) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigGetByUnitIdResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigGetByUnitIDResult) GetSuccess() *core_api.ConfigGetByUnitIdResp {
	if !p.IsSetSuccess() {
		return ConfigGetByUnitIDResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigGetByUnitIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.ConfigGetByUnitIdResp)
}

func (p *ConfigGetByUnitIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigGetByUnitIDResult) GetResult() interface{} {
	return p.Success
}

func configGetCharacterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigGetCharacterReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Config).ConfigGetCharacter(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigGetCharacterArgs:
		success, err := handler.(core_api.Config).ConfigGetCharacter(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigGetCharacterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigGetCharacterArgs() interface{} {
	return &ConfigGetCharacterArgs{}
}

func newConfigGetCharacterResult() interface{} {
	return &ConfigGetCharacterResult{}
}

type ConfigGetCharacterArgs struct {
	Req *core_api.ConfigGetCharacterReq
}

func (p *ConfigGetCharacterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigGetCharacterArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigGetCharacterReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigGetCharacterArgs_Req_DEFAULT *core_api.ConfigGetCharacterReq

func (p *ConfigGetCharacterArgs) GetReq() *core_api.ConfigGetCharacterReq {
	if !p.IsSetReq() {
		return ConfigGetCharacterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigGetCharacterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigGetCharacterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigGetCharacterResult struct {
	Success *core_api.ConfigGetCharacterResp
}

var ConfigGetCharacterResult_Success_DEFAULT *core_api.ConfigGetCharacterResp

func (p *ConfigGetCharacterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigGetCharacterResult) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigGetCharacterResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigGetCharacterResult) GetSuccess() *core_api.ConfigGetCharacterResp {
	if !p.IsSetSuccess() {
		return ConfigGetCharacterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigGetCharacterResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.ConfigGetCharacterResp)
}

func (p *ConfigGetCharacterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigGetCharacterResult) GetResult() interface{} {
	return p.Success
}

func configListVoiceHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigListVoiceReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Config).ConfigListVoice(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigListVoiceArgs:
		success, err := handler.(core_api.Config).ConfigListVoice(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigListVoiceResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigListVoiceArgs() interface{} {
	return &ConfigListVoiceArgs{}
}

func newConfigListVoiceResult() interface{} {
	return &ConfigListVoiceResult{}
}

type ConfigListVoiceArgs struct {
	Req *core_api.ConfigListVoiceReq
}

func (p *ConfigListVoiceArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigListVoiceArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigListVoiceReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigListVoiceArgs_Req_DEFAULT *core_api.ConfigListVoiceReq

func (p *ConfigListVoiceArgs) GetReq() *core_api.ConfigListVoiceReq {
	if !p.IsSetReq() {
		return ConfigListVoiceArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigListVoiceArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigListVoiceArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigListVoiceResult struct {
	Success *core_api.ConfigListVoiceResp
}

var ConfigListVoiceResult_Success_DEFAULT *core_api.ConfigListVoiceResp

func (p *ConfigListVoiceResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigListVoiceResult) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigListVoiceResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigListVoiceResult) GetSuccess() *core_api.ConfigListVoiceResp {
	if !p.IsSetSuccess() {
		return ConfigListVoiceResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigListVoiceResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.ConfigListVoiceResp)
}

func (p *ConfigListVoiceResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigListVoiceResult) GetResult() interface{} {
	return p.Success
}

func configAddCharacterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigAddCharacterReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Config).ConfigAddCharacter(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigAddCharacterArgs:
		success, err := handler.(core_api.Config).ConfigAddCharacter(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigAddCharacterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigAddCharacterArgs() interface{} {
	return &ConfigAddCharacterArgs{}
}

func newConfigAddCharacterResult() interface{} {
	return &ConfigAddCharacterResult{}
}

type ConfigAddCharacterArgs struct {
	Req *core_api.ConfigAddCharacterReq
}

func (p *ConfigAddCharacterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigAddCharacterArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigAddCharacterReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigAddCharacterArgs_Req_DEFAULT *core_api.ConfigAddCharacterReq

func (p *ConfigAddCharacterArgs) GetReq() *core_api.ConfigAddCharacterReq {
	if !p.IsSetReq() {
		return ConfigAddCharacterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigAddCharacterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigAddCharacterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigAddCharacterResult struct {
	Success *core_api.ConfigAddCharacterResp
}

var ConfigAddCharacterResult_Success_DEFAULT *core_api.ConfigAddCharacterResp

func (p *ConfigAddCharacterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigAddCharacterResult) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigAddCharacterResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigAddCharacterResult) GetSuccess() *core_api.ConfigAddCharacterResp {
	if !p.IsSetSuccess() {
		return ConfigAddCharacterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigAddCharacterResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.ConfigAddCharacterResp)
}

func (p *ConfigAddCharacterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigAddCharacterResult) GetResult() interface{} {
	return p.Success
}

func configUpdateCharacterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigUpdateCharacterReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Config).ConfigUpdateCharacter(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigUpdateCharacterArgs:
		success, err := handler.(core_api.Config).ConfigUpdateCharacter(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigUpdateCharacterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigUpdateCharacterArgs() interface{} {
	return &ConfigUpdateCharacterArgs{}
}

func newConfigUpdateCharacterResult() interface{} {
	return &ConfigUpdateCharacterResult{}
}

type ConfigUpdateCharacterArgs struct {
	Req *core_api.ConfigUpdateCharacterReq
}

func (p *ConfigUpdateCharacterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigUpdateCharacterArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigUpdateCharacterReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigUpdateCharacterArgs_Req_DEFAULT *core_api.ConfigUpdateCharacterReq

func (p *ConfigUpdateCharacterArgs) GetReq() *core_api.ConfigUpdateCharacterReq {
	if !p.IsSetReq() {
		return ConfigUpdateCharacterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigUpdateCharacterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigUpdateCharacterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigUpdateCharacterResult struct {
	Success *core_api.ConfigUpdateCharacterResp
}

var ConfigUpdateCharacterResult_Success_DEFAULT *core_api.ConfigUpdateCharacterResp

func (p *ConfigUpdateCharacterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigUpdateCharacterResult) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigUpdateCharacterResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigUpdateCharacterResult) GetSuccess() *core_api.ConfigUpdateCharacterResp {
	if !p.IsSetSuccess() {
		return ConfigUpdateCharacterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigUpdateCharacterResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.ConfigUpdateCharacterResp)
}

func (p *ConfigUpdateCharacterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigUpdateCharacterResult) GetResult() interface{} {
	return p.Success
}

func configDeleteCharacterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigDeleteCharacterReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.Config).ConfigDeleteCharacter(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigDeleteCharacterArgs:
		success, err := handler.(core_api.Config).ConfigDeleteCharacter(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigDeleteCharacterResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigDeleteCharacterArgs() interface{} {
	return &ConfigDeleteCharacterArgs{}
}

func newConfigDeleteCharacterResult() interface{} {
	return &ConfigDeleteCharacterResult{}
}

type ConfigDeleteCharacterArgs struct {
	Req *core_api.ConfigDeleteCharacterReq
}

func (p *ConfigDeleteCharacterArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigDeleteCharacterArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigDeleteCharacterReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigDeleteCharacterArgs_Req_DEFAULT *core_api.ConfigDeleteCharacterReq

func (p *ConfigDeleteCharacterArgs) GetReq() *core_api.ConfigDeleteCharacterReq {
	if !p.IsSetReq() {
		return ConfigDeleteCharacterArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigDeleteCharacterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigDeleteCharacterArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigDeleteCharacterResult struct {
	Success *core_api.ConfigDeleteCharacterResp
}

var ConfigDeleteCharacterResult_Success_DEFAULT *core_api.ConfigDeleteCharacterResp

func (p *ConfigDeleteCharacterResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigDeleteCharacterResult) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigDeleteCharacterResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigDeleteCharacterResult) GetSuccess() *core_api.ConfigDeleteCharacterResp {
	if !p.IsSetSuccess() {
		return ConfigDeleteCharacterResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigDeleteCharacterResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.ConfigDeleteCharacterResp)
}

func (p *ConfigDeleteCharacterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigDeleteCharacterResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ConfigCreate(ctx context.Context, Req *core_api.ConfigCreateOrUpdateReq) (r *basic.Response, err error) {
	var _args ConfigCreateArgs
	_args.Req = Req
	var _result ConfigCreateResult
	if err = p.c.Call(ctx, "ConfigCreate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigUpdateInfo(ctx context.Context, Req *core_api.ConfigCreateOrUpdateReq) (r *basic.Response, err error) {
	var _args ConfigUpdateInfoArgs
	_args.Req = Req
	var _result ConfigUpdateInfoResult
	if err = p.c.Call(ctx, "ConfigUpdateInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigGetByUnitID(ctx context.Context, Req *core_api.ConfigGetByUnitIdReq) (r *core_api.ConfigGetByUnitIdResp, err error) {
	var _args ConfigGetByUnitIDArgs
	_args.Req = Req
	var _result ConfigGetByUnitIDResult
	if err = p.c.Call(ctx, "ConfigGetByUnitID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigGetCharacter(ctx context.Context, Req *core_api.ConfigGetCharacterReq) (r *core_api.ConfigGetCharacterResp, err error) {
	var _args ConfigGetCharacterArgs
	_args.Req = Req
	var _result ConfigGetCharacterResult
	if err = p.c.Call(ctx, "ConfigGetCharacter", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigListVoice(ctx context.Context, Req *core_api.ConfigListVoiceReq) (r *core_api.ConfigListVoiceResp, err error) {
	var _args ConfigListVoiceArgs
	_args.Req = Req
	var _result ConfigListVoiceResult
	if err = p.c.Call(ctx, "ConfigListVoice", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigAddCharacter(ctx context.Context, Req *core_api.ConfigAddCharacterReq) (r *core_api.ConfigAddCharacterResp, err error) {
	var _args ConfigAddCharacterArgs
	_args.Req = Req
	var _result ConfigAddCharacterResult
	if err = p.c.Call(ctx, "ConfigAddCharacter", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigUpdateCharacter(ctx context.Context, Req *core_api.ConfigUpdateCharacterReq) (r *core_api.ConfigUpdateCharacterResp, err error) {
	var _args ConfigUpdateCharacterArgs
	_args.Req = Req
	var _result ConfigUpdateCharacterResult
	if err = p.c.Call(ctx, "ConfigUpdateCharacter", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigDeleteCharacter(ctx context.Context, Req *core_api.ConfigDeleteCharacterReq) (r *core_api.ConfigDeleteCharacterResp, err error) {
	var _args ConfigDeleteCharacterArgs
	_args.Req = Req
	var _result ConfigDeleteCharacterResult
	if err = p.c.Call(ctx, "ConfigDeleteCharacter", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
