// Code generated by Kitex v0.15.4. DO NOT EDIT.

package psychdashboardservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	core_api "github.com/xh-polaris/psych-idl/kitex_gen/core_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"DashboardGetDataOverview": kitex.NewMethodInfo(
		dashboardGetDataOverviewHandler,
		newDashboardGetDataOverviewArgs,
		newDashboardGetDataOverviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetAlarmOverview": kitex.NewMethodInfo(
		dashboardGetAlarmOverviewHandler,
		newDashboardGetAlarmOverviewArgs,
		newDashboardGetAlarmOverviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListAlarmUsers": kitex.NewMethodInfo(
		dashboardListAlarmUsersHandler,
		newDashboardListAlarmUsersArgs,
		newDashboardListAlarmUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListClasses": kitex.NewMethodInfo(
		dashboardListClassesHandler,
		newDashboardListClassesArgs,
		newDashboardListClassesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListUsers": kitex.NewMethodInfo(
		dashboardListUsersHandler,
		newDashboardListUsersArgs,
		newDashboardListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	psychDashboardServiceServiceInfo                = NewServiceInfo()
	psychDashboardServiceServiceInfoForClient       = NewServiceInfoForClient()
	psychDashboardServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return psychDashboardServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return psychDashboardServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return psychDashboardServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PsychDashboardService"
	handlerType := (*core_api.PsychDashboardService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "core_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func dashboardGetDataOverviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetDataOverviewReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.PsychDashboardService).DashboardGetDataOverview(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetDataOverviewArgs:
		success, err := handler.(core_api.PsychDashboardService).DashboardGetDataOverview(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetDataOverviewResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetDataOverviewArgs() interface{} {
	return &DashboardGetDataOverviewArgs{}
}

func newDashboardGetDataOverviewResult() interface{} {
	return &DashboardGetDataOverviewResult{}
}

type DashboardGetDataOverviewArgs struct {
	Req *core_api.DashboardGetDataOverviewReq
}

func (p *DashboardGetDataOverviewArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetDataOverviewArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataOverviewReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetDataOverviewArgs_Req_DEFAULT *core_api.DashboardGetDataOverviewReq

func (p *DashboardGetDataOverviewArgs) GetReq() *core_api.DashboardGetDataOverviewReq {
	if !p.IsSetReq() {
		return DashboardGetDataOverviewArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetDataOverviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetDataOverviewArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetDataOverviewResult struct {
	Success *core_api.DashboardGetDataOverviewResp
}

var DashboardGetDataOverviewResult_Success_DEFAULT *core_api.DashboardGetDataOverviewResp

func (p *DashboardGetDataOverviewResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetDataOverviewResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataOverviewResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetDataOverviewResult) GetSuccess() *core_api.DashboardGetDataOverviewResp {
	if !p.IsSetSuccess() {
		return DashboardGetDataOverviewResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetDataOverviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetDataOverviewResp)
}

func (p *DashboardGetDataOverviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetDataOverviewResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetAlarmOverviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetAlarmOverviewReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.PsychDashboardService).DashboardGetAlarmOverview(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetAlarmOverviewArgs:
		success, err := handler.(core_api.PsychDashboardService).DashboardGetAlarmOverview(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetAlarmOverviewResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetAlarmOverviewArgs() interface{} {
	return &DashboardGetAlarmOverviewArgs{}
}

func newDashboardGetAlarmOverviewResult() interface{} {
	return &DashboardGetAlarmOverviewResult{}
}

type DashboardGetAlarmOverviewArgs struct {
	Req *core_api.DashboardGetAlarmOverviewReq
}

func (p *DashboardGetAlarmOverviewArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetAlarmOverviewArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetAlarmOverviewReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetAlarmOverviewArgs_Req_DEFAULT *core_api.DashboardGetAlarmOverviewReq

func (p *DashboardGetAlarmOverviewArgs) GetReq() *core_api.DashboardGetAlarmOverviewReq {
	if !p.IsSetReq() {
		return DashboardGetAlarmOverviewArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetAlarmOverviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetAlarmOverviewArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetAlarmOverviewResult struct {
	Success *core_api.DashboardGetAlarmOverviewResp
}

var DashboardGetAlarmOverviewResult_Success_DEFAULT *core_api.DashboardGetAlarmOverviewResp

func (p *DashboardGetAlarmOverviewResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetAlarmOverviewResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetAlarmOverviewResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetAlarmOverviewResult) GetSuccess() *core_api.DashboardGetAlarmOverviewResp {
	if !p.IsSetSuccess() {
		return DashboardGetAlarmOverviewResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetAlarmOverviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetAlarmOverviewResp)
}

func (p *DashboardGetAlarmOverviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetAlarmOverviewResult) GetResult() interface{} {
	return p.Success
}

func dashboardListAlarmUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListAlarmRecordsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.PsychDashboardService).DashboardListAlarmUsers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListAlarmUsersArgs:
		success, err := handler.(core_api.PsychDashboardService).DashboardListAlarmUsers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListAlarmUsersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListAlarmUsersArgs() interface{} {
	return &DashboardListAlarmUsersArgs{}
}

func newDashboardListAlarmUsersResult() interface{} {
	return &DashboardListAlarmUsersResult{}
}

type DashboardListAlarmUsersArgs struct {
	Req *core_api.DashboardListAlarmRecordsReq
}

func (p *DashboardListAlarmUsersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListAlarmUsersArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListAlarmRecordsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListAlarmUsersArgs_Req_DEFAULT *core_api.DashboardListAlarmRecordsReq

func (p *DashboardListAlarmUsersArgs) GetReq() *core_api.DashboardListAlarmRecordsReq {
	if !p.IsSetReq() {
		return DashboardListAlarmUsersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListAlarmUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListAlarmUsersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListAlarmUsersResult struct {
	Success *core_api.DashboardListAlarmRecordsReq
}

var DashboardListAlarmUsersResult_Success_DEFAULT *core_api.DashboardListAlarmRecordsReq

func (p *DashboardListAlarmUsersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListAlarmUsersResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListAlarmRecordsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListAlarmUsersResult) GetSuccess() *core_api.DashboardListAlarmRecordsReq {
	if !p.IsSetSuccess() {
		return DashboardListAlarmUsersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListAlarmUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListAlarmRecordsReq)
}

func (p *DashboardListAlarmUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListAlarmUsersResult) GetResult() interface{} {
	return p.Success
}

func dashboardListClassesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListClassesReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.PsychDashboardService).DashboardListClasses(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListClassesArgs:
		success, err := handler.(core_api.PsychDashboardService).DashboardListClasses(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListClassesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListClassesArgs() interface{} {
	return &DashboardListClassesArgs{}
}

func newDashboardListClassesResult() interface{} {
	return &DashboardListClassesResult{}
}

type DashboardListClassesArgs struct {
	Req *core_api.DashboardListClassesReq
}

func (p *DashboardListClassesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListClassesArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListClassesReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListClassesArgs_Req_DEFAULT *core_api.DashboardListClassesReq

func (p *DashboardListClassesArgs) GetReq() *core_api.DashboardListClassesReq {
	if !p.IsSetReq() {
		return DashboardListClassesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListClassesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListClassesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListClassesResult struct {
	Success *core_api.DashboardListClassesResp
}

var DashboardListClassesResult_Success_DEFAULT *core_api.DashboardListClassesResp

func (p *DashboardListClassesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListClassesResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListClassesResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListClassesResult) GetSuccess() *core_api.DashboardListClassesResp {
	if !p.IsSetSuccess() {
		return DashboardListClassesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListClassesResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListClassesResp)
}

func (p *DashboardListClassesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListClassesResult) GetResult() interface{} {
	return p.Success
}

func dashboardListUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListUsersReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.PsychDashboardService).DashboardListUsers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListUsersArgs:
		success, err := handler.(core_api.PsychDashboardService).DashboardListUsers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListUsersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListUsersArgs() interface{} {
	return &DashboardListUsersArgs{}
}

func newDashboardListUsersResult() interface{} {
	return &DashboardListUsersResult{}
}

type DashboardListUsersArgs struct {
	Req *core_api.DashboardListUsersReq
}

func (p *DashboardListUsersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListUsersArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUsersReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListUsersArgs_Req_DEFAULT *core_api.DashboardListUsersReq

func (p *DashboardListUsersArgs) GetReq() *core_api.DashboardListUsersReq {
	if !p.IsSetReq() {
		return DashboardListUsersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListUsersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListUsersResult struct {
	Success *core_api.DashboardListUsersResp
}

var DashboardListUsersResult_Success_DEFAULT *core_api.DashboardListUsersResp

func (p *DashboardListUsersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListUsersResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUsersResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListUsersResult) GetSuccess() *core_api.DashboardListUsersResp {
	if !p.IsSetSuccess() {
		return DashboardListUsersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListUsersResp)
}

func (p *DashboardListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListUsersResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DashboardGetDataOverview(ctx context.Context, Req *core_api.DashboardGetDataOverviewReq) (r *core_api.DashboardGetDataOverviewResp, err error) {
	var _args DashboardGetDataOverviewArgs
	_args.Req = Req
	var _result DashboardGetDataOverviewResult
	if err = p.c.Call(ctx, "DashboardGetDataOverview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetAlarmOverview(ctx context.Context, Req *core_api.DashboardGetAlarmOverviewReq) (r *core_api.DashboardGetAlarmOverviewResp, err error) {
	var _args DashboardGetAlarmOverviewArgs
	_args.Req = Req
	var _result DashboardGetAlarmOverviewResult
	if err = p.c.Call(ctx, "DashboardGetAlarmOverview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListAlarmUsers(ctx context.Context, Req *core_api.DashboardListAlarmRecordsReq) (r *core_api.DashboardListAlarmRecordsReq, err error) {
	var _args DashboardListAlarmUsersArgs
	_args.Req = Req
	var _result DashboardListAlarmUsersResult
	if err = p.c.Call(ctx, "DashboardListAlarmUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListClasses(ctx context.Context, Req *core_api.DashboardListClassesReq) (r *core_api.DashboardListClassesResp, err error) {
	var _args DashboardListClassesArgs
	_args.Req = Req
	var _result DashboardListClassesResult
	if err = p.c.Call(ctx, "DashboardListClasses", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListUsers(ctx context.Context, Req *core_api.DashboardListUsersReq) (r *core_api.DashboardListUsersResp, err error) {
	var _args DashboardListUsersArgs
	_args.Req = Req
	var _result DashboardListUsersResult
	if err = p.c.Call(ctx, "DashboardListUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
