// Code generated by Kitex v0.15.4. DO NOT EDIT.

package coreapi

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	core_api "github.com/xh-polaris/psych-idl/kitex_gen/core_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UserSignIn": kitex.NewMethodInfo(
		userSignInHandler,
		newUserSignInArgs,
		newUserSignInResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserGetInfo": kitex.NewMethodInfo(
		userGetInfoHandler,
		newUserGetInfoArgs,
		newUserGetInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	coreApiServiceInfo                = NewServiceInfo()
	coreApiServiceInfoForClient       = NewServiceInfoForClient()
	coreApiServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return coreApiServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return coreApiServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return coreApiServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CoreApi"
	handlerType := (*core_api.CoreApi)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "core_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func userSignInHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UserSignInReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UserSignIn(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserSignInArgs:
		success, err := handler.(core_api.CoreApi).UserSignIn(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserSignInResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserSignInArgs() interface{} {
	return &UserSignInArgs{}
}

func newUserSignInResult() interface{} {
	return &UserSignInResult{}
}

type UserSignInArgs struct {
	Req *core_api.UserSignInReq
}

func (p *UserSignInArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserSignInArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UserSignInReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserSignInArgs_Req_DEFAULT *core_api.UserSignInReq

func (p *UserSignInArgs) GetReq() *core_api.UserSignInReq {
	if !p.IsSetReq() {
		return UserSignInArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserSignInArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSignInArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserSignInResult struct {
	Success *core_api.UserSignInResp
}

var UserSignInResult_Success_DEFAULT *core_api.UserSignInResp

func (p *UserSignInResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserSignInResult) Unmarshal(in []byte) error {
	msg := new(core_api.UserSignInResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserSignInResult) GetSuccess() *core_api.UserSignInResp {
	if !p.IsSetSuccess() {
		return UserSignInResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserSignInResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UserSignInResp)
}

func (p *UserSignInResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSignInResult) GetResult() interface{} {
	return p.Success
}

func userGetInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UserGetInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UserGetInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserGetInfoArgs:
		success, err := handler.(core_api.CoreApi).UserGetInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserGetInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserGetInfoArgs() interface{} {
	return &UserGetInfoArgs{}
}

func newUserGetInfoResult() interface{} {
	return &UserGetInfoResult{}
}

type UserGetInfoArgs struct {
	Req *core_api.UserGetInfoReq
}

func (p *UserGetInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserGetInfoArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UserGetInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserGetInfoArgs_Req_DEFAULT *core_api.UserGetInfoReq

func (p *UserGetInfoArgs) GetReq() *core_api.UserGetInfoReq {
	if !p.IsSetReq() {
		return UserGetInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserGetInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserGetInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserGetInfoResult struct {
	Success *core_api.UserGetInfoResp
}

var UserGetInfoResult_Success_DEFAULT *core_api.UserGetInfoResp

func (p *UserGetInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserGetInfoResult) Unmarshal(in []byte) error {
	msg := new(core_api.UserGetInfoResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserGetInfoResult) GetSuccess() *core_api.UserGetInfoResp {
	if !p.IsSetSuccess() {
		return UserGetInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserGetInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UserGetInfoResp)
}

func (p *UserGetInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserGetInfoResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UserSignIn(ctx context.Context, Req *core_api.UserSignInReq) (r *core_api.UserSignInResp, err error) {
	var _args UserSignInArgs
	_args.Req = Req
	var _result UserSignInResult
	if err = p.c.Call(ctx, "UserSignIn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserGetInfo(ctx context.Context, Req *core_api.UserGetInfoReq) (r *core_api.UserGetInfoResp, err error) {
	var _args UserGetInfoArgs
	_args.Req = Req
	var _result UserGetInfoResult
	if err = p.c.Call(ctx, "UserGetInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
