// Code generated by Kitex v0.16.1. DO NOT EDIT.

package coreapi

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	basic "github.com/xh-polaris/psych-idl/kitex_gen/basic"
	core_api "github.com/xh-polaris/psych-idl/kitex_gen/core_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UserSignUp": kitex.NewMethodInfo(
		userSignUpHandler,
		newUserSignUpArgs,
		newUserSignUpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserSignIn": kitex.NewMethodInfo(
		userSignInHandler,
		newUserSignInArgs,
		newUserSignInResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserGetInfo": kitex.NewMethodInfo(
		userGetInfoHandler,
		newUserGetInfoArgs,
		newUserGetInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserUpdateInfo": kitex.NewMethodInfo(
		userUpdateInfoHandler,
		newUserUpdateInfoArgs,
		newUserUpdateInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UserUpdatePassword": kitex.NewMethodInfo(
		userUpdatePasswordHandler,
		newUserUpdatePasswordArgs,
		newUserUpdatePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitSignUp": kitex.NewMethodInfo(
		unitSignUpHandler,
		newUnitSignUpArgs,
		newUnitSignUpResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitSignIn": kitex.NewMethodInfo(
		unitSignInHandler,
		newUnitSignInArgs,
		newUnitSignInResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitGetInfo": kitex.NewMethodInfo(
		unitGetInfoHandler,
		newUnitGetInfoArgs,
		newUnitGetInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitUpdateInfo": kitex.NewMethodInfo(
		unitUpdateInfoHandler,
		newUnitUpdateInfoArgs,
		newUnitUpdateInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitUpdatePassword": kitex.NewMethodInfo(
		unitUpdatePasswordHandler,
		newUnitUpdatePasswordArgs,
		newUnitUpdatePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitLinkUser": kitex.NewMethodInfo(
		unitLinkUserHandler,
		newUnitLinkUserArgs,
		newUnitLinkUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UnitCreateAndLinkUser": kitex.NewMethodInfo(
		unitCreateAndLinkUserHandler,
		newUnitCreateAndLinkUserArgs,
		newUnitCreateAndLinkUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigCreate": kitex.NewMethodInfo(
		configCreateHandler,
		newConfigCreateArgs,
		newConfigCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigUpdateInfo": kitex.NewMethodInfo(
		configUpdateInfoHandler,
		newConfigUpdateInfoArgs,
		newConfigUpdateInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ConfigGetByUnitID": kitex.NewMethodInfo(
		configGetByUnitIDHandler,
		newConfigGetByUnitIDArgs,
		newConfigGetByUnitIDResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetDataOverview": kitex.NewMethodInfo(
		dashboardGetDataOverviewHandler,
		newDashboardGetDataOverviewArgs,
		newDashboardGetDataOverviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetDataTrend": kitex.NewMethodInfo(
		dashboardGetDataTrendHandler,
		newDashboardGetDataTrendArgs,
		newDashboardGetDataTrendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListUnits": kitex.NewMethodInfo(
		dashboardListUnitsHandler,
		newDashboardListUnitsArgs,
		newDashboardListUnitsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetPsychTrend": kitex.NewMethodInfo(
		dashboardGetPsychTrendHandler,
		newDashboardGetPsychTrendArgs,
		newDashboardGetPsychTrendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardGetAlarmOverview": kitex.NewMethodInfo(
		dashboardGetAlarmOverviewHandler,
		newDashboardGetAlarmOverviewArgs,
		newDashboardGetAlarmOverviewResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListAlarmRecords": kitex.NewMethodInfo(
		dashboardListAlarmRecordsHandler,
		newDashboardListAlarmRecordsArgs,
		newDashboardListAlarmRecordsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListClasses": kitex.NewMethodInfo(
		dashboardListClassesHandler,
		newDashboardListClassesArgs,
		newDashboardListClassesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DashboardListUsers": kitex.NewMethodInfo(
		dashboardListUsersHandler,
		newDashboardListUsersArgs,
		newDashboardListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	coreApiServiceInfo                = NewServiceInfo()
	coreApiServiceInfoForClient       = NewServiceInfoForClient()
	coreApiServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return coreApiServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return coreApiServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return coreApiServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CoreApi"
	handlerType := (*core_api.CoreApi)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "core_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func userSignUpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UserSignUpReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UserSignUp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserSignUpArgs:
		success, err := handler.(core_api.CoreApi).UserSignUp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserSignUpResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserSignUpArgs() interface{} {
	return &UserSignUpArgs{}
}

func newUserSignUpResult() interface{} {
	return &UserSignUpResult{}
}

type UserSignUpArgs struct {
	Req *core_api.UserSignUpReq
}

func (p *UserSignUpArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserSignUpArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UserSignUpReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserSignUpArgs_Req_DEFAULT *core_api.UserSignUpReq

func (p *UserSignUpArgs) GetReq() *core_api.UserSignUpReq {
	if !p.IsSetReq() {
		return UserSignUpArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserSignUpArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSignUpArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserSignUpResult struct {
	Success *core_api.UserSignUpResp
}

var UserSignUpResult_Success_DEFAULT *core_api.UserSignUpResp

func (p *UserSignUpResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserSignUpResult) Unmarshal(in []byte) error {
	msg := new(core_api.UserSignUpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserSignUpResult) GetSuccess() *core_api.UserSignUpResp {
	if !p.IsSetSuccess() {
		return UserSignUpResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserSignUpResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UserSignUpResp)
}

func (p *UserSignUpResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSignUpResult) GetResult() interface{} {
	return p.Success
}

func userSignInHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UserSignInReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UserSignIn(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserSignInArgs:
		success, err := handler.(core_api.CoreApi).UserSignIn(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserSignInResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserSignInArgs() interface{} {
	return &UserSignInArgs{}
}

func newUserSignInResult() interface{} {
	return &UserSignInResult{}
}

type UserSignInArgs struct {
	Req *core_api.UserSignInReq
}

func (p *UserSignInArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserSignInArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UserSignInReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserSignInArgs_Req_DEFAULT *core_api.UserSignInReq

func (p *UserSignInArgs) GetReq() *core_api.UserSignInReq {
	if !p.IsSetReq() {
		return UserSignInArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserSignInArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSignInArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserSignInResult struct {
	Success *core_api.UserSignInResp
}

var UserSignInResult_Success_DEFAULT *core_api.UserSignInResp

func (p *UserSignInResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserSignInResult) Unmarshal(in []byte) error {
	msg := new(core_api.UserSignInResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserSignInResult) GetSuccess() *core_api.UserSignInResp {
	if !p.IsSetSuccess() {
		return UserSignInResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserSignInResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UserSignInResp)
}

func (p *UserSignInResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSignInResult) GetResult() interface{} {
	return p.Success
}

func userGetInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UserGetInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UserGetInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserGetInfoArgs:
		success, err := handler.(core_api.CoreApi).UserGetInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserGetInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserGetInfoArgs() interface{} {
	return &UserGetInfoArgs{}
}

func newUserGetInfoResult() interface{} {
	return &UserGetInfoResult{}
}

type UserGetInfoArgs struct {
	Req *core_api.UserGetInfoReq
}

func (p *UserGetInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserGetInfoArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UserGetInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserGetInfoArgs_Req_DEFAULT *core_api.UserGetInfoReq

func (p *UserGetInfoArgs) GetReq() *core_api.UserGetInfoReq {
	if !p.IsSetReq() {
		return UserGetInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserGetInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserGetInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserGetInfoResult struct {
	Success *core_api.UserGetInfoResp
}

var UserGetInfoResult_Success_DEFAULT *core_api.UserGetInfoResp

func (p *UserGetInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserGetInfoResult) Unmarshal(in []byte) error {
	msg := new(core_api.UserGetInfoResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserGetInfoResult) GetSuccess() *core_api.UserGetInfoResp {
	if !p.IsSetSuccess() {
		return UserGetInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserGetInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UserGetInfoResp)
}

func (p *UserGetInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserGetInfoResult) GetResult() interface{} {
	return p.Success
}

func userUpdateInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UserUpdateInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UserUpdateInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserUpdateInfoArgs:
		success, err := handler.(core_api.CoreApi).UserUpdateInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserUpdateInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserUpdateInfoArgs() interface{} {
	return &UserUpdateInfoArgs{}
}

func newUserUpdateInfoResult() interface{} {
	return &UserUpdateInfoResult{}
}

type UserUpdateInfoArgs struct {
	Req *core_api.UserUpdateInfoReq
}

func (p *UserUpdateInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserUpdateInfoArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UserUpdateInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserUpdateInfoArgs_Req_DEFAULT *core_api.UserUpdateInfoReq

func (p *UserUpdateInfoArgs) GetReq() *core_api.UserUpdateInfoReq {
	if !p.IsSetReq() {
		return UserUpdateInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserUpdateInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserUpdateInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserUpdateInfoResult struct {
	Success *basic.Response
}

var UserUpdateInfoResult_Success_DEFAULT *basic.Response

func (p *UserUpdateInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserUpdateInfoResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserUpdateInfoResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UserUpdateInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserUpdateInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UserUpdateInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserUpdateInfoResult) GetResult() interface{} {
	return p.Success
}

func userUpdatePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UserUpdatePasswordReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UserUpdatePassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UserUpdatePasswordArgs:
		success, err := handler.(core_api.CoreApi).UserUpdatePassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UserUpdatePasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUserUpdatePasswordArgs() interface{} {
	return &UserUpdatePasswordArgs{}
}

func newUserUpdatePasswordResult() interface{} {
	return &UserUpdatePasswordResult{}
}

type UserUpdatePasswordArgs struct {
	Req *core_api.UserUpdatePasswordReq
}

func (p *UserUpdatePasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UserUpdatePasswordArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UserUpdatePasswordReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UserUpdatePasswordArgs_Req_DEFAULT *core_api.UserUpdatePasswordReq

func (p *UserUpdatePasswordArgs) GetReq() *core_api.UserUpdatePasswordReq {
	if !p.IsSetReq() {
		return UserUpdatePasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UserUpdatePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserUpdatePasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UserUpdatePasswordResult struct {
	Success *basic.Response
}

var UserUpdatePasswordResult_Success_DEFAULT *basic.Response

func (p *UserUpdatePasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UserUpdatePasswordResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UserUpdatePasswordResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UserUpdatePasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UserUpdatePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UserUpdatePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserUpdatePasswordResult) GetResult() interface{} {
	return p.Success
}

func unitSignUpHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UnitSignUpReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UnitSignUp(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitSignUpArgs:
		success, err := handler.(core_api.CoreApi).UnitSignUp(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitSignUpResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitSignUpArgs() interface{} {
	return &UnitSignUpArgs{}
}

func newUnitSignUpResult() interface{} {
	return &UnitSignUpResult{}
}

type UnitSignUpArgs struct {
	Req *core_api.UnitSignUpReq
}

func (p *UnitSignUpArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitSignUpArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UnitSignUpReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitSignUpArgs_Req_DEFAULT *core_api.UnitSignUpReq

func (p *UnitSignUpArgs) GetReq() *core_api.UnitSignUpReq {
	if !p.IsSetReq() {
		return UnitSignUpArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitSignUpArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitSignUpArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitSignUpResult struct {
	Success *core_api.UnitSignUpResp
}

var UnitSignUpResult_Success_DEFAULT *core_api.UnitSignUpResp

func (p *UnitSignUpResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitSignUpResult) Unmarshal(in []byte) error {
	msg := new(core_api.UnitSignUpResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitSignUpResult) GetSuccess() *core_api.UnitSignUpResp {
	if !p.IsSetSuccess() {
		return UnitSignUpResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitSignUpResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UnitSignUpResp)
}

func (p *UnitSignUpResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitSignUpResult) GetResult() interface{} {
	return p.Success
}

func unitSignInHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UnitSignInReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UnitSignIn(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitSignInArgs:
		success, err := handler.(core_api.CoreApi).UnitSignIn(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitSignInResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitSignInArgs() interface{} {
	return &UnitSignInArgs{}
}

func newUnitSignInResult() interface{} {
	return &UnitSignInResult{}
}

type UnitSignInArgs struct {
	Req *core_api.UnitSignInReq
}

func (p *UnitSignInArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitSignInArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UnitSignInReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitSignInArgs_Req_DEFAULT *core_api.UnitSignInReq

func (p *UnitSignInArgs) GetReq() *core_api.UnitSignInReq {
	if !p.IsSetReq() {
		return UnitSignInArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitSignInArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitSignInArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitSignInResult struct {
	Success *core_api.UnitSignInResp
}

var UnitSignInResult_Success_DEFAULT *core_api.UnitSignInResp

func (p *UnitSignInResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitSignInResult) Unmarshal(in []byte) error {
	msg := new(core_api.UnitSignInResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitSignInResult) GetSuccess() *core_api.UnitSignInResp {
	if !p.IsSetSuccess() {
		return UnitSignInResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitSignInResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UnitSignInResp)
}

func (p *UnitSignInResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitSignInResult) GetResult() interface{} {
	return p.Success
}

func unitGetInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UnitGetInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UnitGetInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitGetInfoArgs:
		success, err := handler.(core_api.CoreApi).UnitGetInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitGetInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitGetInfoArgs() interface{} {
	return &UnitGetInfoArgs{}
}

func newUnitGetInfoResult() interface{} {
	return &UnitGetInfoResult{}
}

type UnitGetInfoArgs struct {
	Req *core_api.UnitGetInfoReq
}

func (p *UnitGetInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitGetInfoArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UnitGetInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitGetInfoArgs_Req_DEFAULT *core_api.UnitGetInfoReq

func (p *UnitGetInfoArgs) GetReq() *core_api.UnitGetInfoReq {
	if !p.IsSetReq() {
		return UnitGetInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitGetInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitGetInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitGetInfoResult struct {
	Success *core_api.UnitGetInfoResp
}

var UnitGetInfoResult_Success_DEFAULT *core_api.UnitGetInfoResp

func (p *UnitGetInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitGetInfoResult) Unmarshal(in []byte) error {
	msg := new(core_api.UnitGetInfoResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitGetInfoResult) GetSuccess() *core_api.UnitGetInfoResp {
	if !p.IsSetSuccess() {
		return UnitGetInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitGetInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UnitGetInfoResp)
}

func (p *UnitGetInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitGetInfoResult) GetResult() interface{} {
	return p.Success
}

func unitUpdateInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UnitUpdateInfoReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UnitUpdateInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitUpdateInfoArgs:
		success, err := handler.(core_api.CoreApi).UnitUpdateInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitUpdateInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitUpdateInfoArgs() interface{} {
	return &UnitUpdateInfoArgs{}
}

func newUnitUpdateInfoResult() interface{} {
	return &UnitUpdateInfoResult{}
}

type UnitUpdateInfoArgs struct {
	Req *core_api.UnitUpdateInfoReq
}

func (p *UnitUpdateInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitUpdateInfoArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UnitUpdateInfoReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitUpdateInfoArgs_Req_DEFAULT *core_api.UnitUpdateInfoReq

func (p *UnitUpdateInfoArgs) GetReq() *core_api.UnitUpdateInfoReq {
	if !p.IsSetReq() {
		return UnitUpdateInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitUpdateInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitUpdateInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitUpdateInfoResult struct {
	Success *basic.Response
}

var UnitUpdateInfoResult_Success_DEFAULT *basic.Response

func (p *UnitUpdateInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitUpdateInfoResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitUpdateInfoResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UnitUpdateInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitUpdateInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UnitUpdateInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitUpdateInfoResult) GetResult() interface{} {
	return p.Success
}

func unitUpdatePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UnitUpdatePasswordReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UnitUpdatePassword(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitUpdatePasswordArgs:
		success, err := handler.(core_api.CoreApi).UnitUpdatePassword(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitUpdatePasswordResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitUpdatePasswordArgs() interface{} {
	return &UnitUpdatePasswordArgs{}
}

func newUnitUpdatePasswordResult() interface{} {
	return &UnitUpdatePasswordResult{}
}

type UnitUpdatePasswordArgs struct {
	Req *core_api.UnitUpdatePasswordReq
}

func (p *UnitUpdatePasswordArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitUpdatePasswordArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UnitUpdatePasswordReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitUpdatePasswordArgs_Req_DEFAULT *core_api.UnitUpdatePasswordReq

func (p *UnitUpdatePasswordArgs) GetReq() *core_api.UnitUpdatePasswordReq {
	if !p.IsSetReq() {
		return UnitUpdatePasswordArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitUpdatePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitUpdatePasswordArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitUpdatePasswordResult struct {
	Success *basic.Response
}

var UnitUpdatePasswordResult_Success_DEFAULT *basic.Response

func (p *UnitUpdatePasswordResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitUpdatePasswordResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitUpdatePasswordResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UnitUpdatePasswordResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitUpdatePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UnitUpdatePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitUpdatePasswordResult) GetResult() interface{} {
	return p.Success
}

func unitLinkUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UnitLinkUserReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UnitLinkUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitLinkUserArgs:
		success, err := handler.(core_api.CoreApi).UnitLinkUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitLinkUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitLinkUserArgs() interface{} {
	return &UnitLinkUserArgs{}
}

func newUnitLinkUserResult() interface{} {
	return &UnitLinkUserResult{}
}

type UnitLinkUserArgs struct {
	Req *core_api.UnitLinkUserReq
}

func (p *UnitLinkUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitLinkUserArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UnitLinkUserReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitLinkUserArgs_Req_DEFAULT *core_api.UnitLinkUserReq

func (p *UnitLinkUserArgs) GetReq() *core_api.UnitLinkUserReq {
	if !p.IsSetReq() {
		return UnitLinkUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitLinkUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitLinkUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitLinkUserResult struct {
	Success *basic.Response
}

var UnitLinkUserResult_Success_DEFAULT *basic.Response

func (p *UnitLinkUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitLinkUserResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitLinkUserResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return UnitLinkUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitLinkUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *UnitLinkUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitLinkUserResult) GetResult() interface{} {
	return p.Success
}

func unitCreateAndLinkUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.UnitCreateAndLinkUserReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).UnitCreateAndLinkUser(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnitCreateAndLinkUserArgs:
		success, err := handler.(core_api.CoreApi).UnitCreateAndLinkUser(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnitCreateAndLinkUserResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnitCreateAndLinkUserArgs() interface{} {
	return &UnitCreateAndLinkUserArgs{}
}

func newUnitCreateAndLinkUserResult() interface{} {
	return &UnitCreateAndLinkUserResult{}
}

type UnitCreateAndLinkUserArgs struct {
	Req *core_api.UnitCreateAndLinkUserReq
}

func (p *UnitCreateAndLinkUserArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnitCreateAndLinkUserArgs) Unmarshal(in []byte) error {
	msg := new(core_api.UnitCreateAndLinkUserReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnitCreateAndLinkUserArgs_Req_DEFAULT *core_api.UnitCreateAndLinkUserReq

func (p *UnitCreateAndLinkUserArgs) GetReq() *core_api.UnitCreateAndLinkUserReq {
	if !p.IsSetReq() {
		return UnitCreateAndLinkUserArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnitCreateAndLinkUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnitCreateAndLinkUserArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnitCreateAndLinkUserResult struct {
	Success *core_api.UnitCreateAndLinkUserResp
}

var UnitCreateAndLinkUserResult_Success_DEFAULT *core_api.UnitCreateAndLinkUserResp

func (p *UnitCreateAndLinkUserResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnitCreateAndLinkUserResult) Unmarshal(in []byte) error {
	msg := new(core_api.UnitCreateAndLinkUserResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnitCreateAndLinkUserResult) GetSuccess() *core_api.UnitCreateAndLinkUserResp {
	if !p.IsSetSuccess() {
		return UnitCreateAndLinkUserResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnitCreateAndLinkUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.UnitCreateAndLinkUserResp)
}

func (p *UnitCreateAndLinkUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnitCreateAndLinkUserResult) GetResult() interface{} {
	return p.Success
}

func configCreateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigCreateOrUpdateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).ConfigCreate(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigCreateArgs:
		success, err := handler.(core_api.CoreApi).ConfigCreate(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigCreateResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigCreateArgs() interface{} {
	return &ConfigCreateArgs{}
}

func newConfigCreateResult() interface{} {
	return &ConfigCreateResult{}
}

type ConfigCreateArgs struct {
	Req *core_api.ConfigCreateOrUpdateReq
}

func (p *ConfigCreateArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigCreateArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigCreateOrUpdateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigCreateArgs_Req_DEFAULT *core_api.ConfigCreateOrUpdateReq

func (p *ConfigCreateArgs) GetReq() *core_api.ConfigCreateOrUpdateReq {
	if !p.IsSetReq() {
		return ConfigCreateArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigCreateArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigCreateArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigCreateResult struct {
	Success *basic.Response
}

var ConfigCreateResult_Success_DEFAULT *basic.Response

func (p *ConfigCreateResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigCreateResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigCreateResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return ConfigCreateResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigCreateResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *ConfigCreateResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigCreateResult) GetResult() interface{} {
	return p.Success
}

func configUpdateInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigCreateOrUpdateReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).ConfigUpdateInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigUpdateInfoArgs:
		success, err := handler.(core_api.CoreApi).ConfigUpdateInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigUpdateInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigUpdateInfoArgs() interface{} {
	return &ConfigUpdateInfoArgs{}
}

func newConfigUpdateInfoResult() interface{} {
	return &ConfigUpdateInfoResult{}
}

type ConfigUpdateInfoArgs struct {
	Req *core_api.ConfigCreateOrUpdateReq
}

func (p *ConfigUpdateInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigUpdateInfoArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigCreateOrUpdateReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigUpdateInfoArgs_Req_DEFAULT *core_api.ConfigCreateOrUpdateReq

func (p *ConfigUpdateInfoArgs) GetReq() *core_api.ConfigCreateOrUpdateReq {
	if !p.IsSetReq() {
		return ConfigUpdateInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigUpdateInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigUpdateInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigUpdateInfoResult struct {
	Success *basic.Response
}

var ConfigUpdateInfoResult_Success_DEFAULT *basic.Response

func (p *ConfigUpdateInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigUpdateInfoResult) Unmarshal(in []byte) error {
	msg := new(basic.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigUpdateInfoResult) GetSuccess() *basic.Response {
	if !p.IsSetSuccess() {
		return ConfigUpdateInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigUpdateInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*basic.Response)
}

func (p *ConfigUpdateInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigUpdateInfoResult) GetResult() interface{} {
	return p.Success
}

func configGetByUnitIDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.ConfigGetByUnitIdReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).ConfigGetByUnitID(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ConfigGetByUnitIDArgs:
		success, err := handler.(core_api.CoreApi).ConfigGetByUnitID(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ConfigGetByUnitIDResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newConfigGetByUnitIDArgs() interface{} {
	return &ConfigGetByUnitIDArgs{}
}

func newConfigGetByUnitIDResult() interface{} {
	return &ConfigGetByUnitIDResult{}
}

type ConfigGetByUnitIDArgs struct {
	Req *core_api.ConfigGetByUnitIdReq
}

func (p *ConfigGetByUnitIDArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ConfigGetByUnitIDArgs) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigGetByUnitIdReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ConfigGetByUnitIDArgs_Req_DEFAULT *core_api.ConfigGetByUnitIdReq

func (p *ConfigGetByUnitIDArgs) GetReq() *core_api.ConfigGetByUnitIdReq {
	if !p.IsSetReq() {
		return ConfigGetByUnitIDArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ConfigGetByUnitIDArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConfigGetByUnitIDArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ConfigGetByUnitIDResult struct {
	Success *core_api.ConfigGetByUnitIdResp
}

var ConfigGetByUnitIDResult_Success_DEFAULT *core_api.ConfigGetByUnitIdResp

func (p *ConfigGetByUnitIDResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ConfigGetByUnitIDResult) Unmarshal(in []byte) error {
	msg := new(core_api.ConfigGetByUnitIdResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ConfigGetByUnitIDResult) GetSuccess() *core_api.ConfigGetByUnitIdResp {
	if !p.IsSetSuccess() {
		return ConfigGetByUnitIDResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ConfigGetByUnitIDResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.ConfigGetByUnitIdResp)
}

func (p *ConfigGetByUnitIDResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConfigGetByUnitIDResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetDataOverviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetDataOverviewReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).DashboardGetDataOverview(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetDataOverviewArgs:
		success, err := handler.(core_api.CoreApi).DashboardGetDataOverview(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetDataOverviewResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetDataOverviewArgs() interface{} {
	return &DashboardGetDataOverviewArgs{}
}

func newDashboardGetDataOverviewResult() interface{} {
	return &DashboardGetDataOverviewResult{}
}

type DashboardGetDataOverviewArgs struct {
	Req *core_api.DashboardGetDataOverviewReq
}

func (p *DashboardGetDataOverviewArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetDataOverviewArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataOverviewReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetDataOverviewArgs_Req_DEFAULT *core_api.DashboardGetDataOverviewReq

func (p *DashboardGetDataOverviewArgs) GetReq() *core_api.DashboardGetDataOverviewReq {
	if !p.IsSetReq() {
		return DashboardGetDataOverviewArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetDataOverviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetDataOverviewArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetDataOverviewResult struct {
	Success *core_api.DashboardGetDataOverviewResp
}

var DashboardGetDataOverviewResult_Success_DEFAULT *core_api.DashboardGetDataOverviewResp

func (p *DashboardGetDataOverviewResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetDataOverviewResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataOverviewResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetDataOverviewResult) GetSuccess() *core_api.DashboardGetDataOverviewResp {
	if !p.IsSetSuccess() {
		return DashboardGetDataOverviewResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetDataOverviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetDataOverviewResp)
}

func (p *DashboardGetDataOverviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetDataOverviewResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetDataTrendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetDataTrendReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).DashboardGetDataTrend(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetDataTrendArgs:
		success, err := handler.(core_api.CoreApi).DashboardGetDataTrend(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetDataTrendResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetDataTrendArgs() interface{} {
	return &DashboardGetDataTrendArgs{}
}

func newDashboardGetDataTrendResult() interface{} {
	return &DashboardGetDataTrendResult{}
}

type DashboardGetDataTrendArgs struct {
	Req *core_api.DashboardGetDataTrendReq
}

func (p *DashboardGetDataTrendArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetDataTrendArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataTrendReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetDataTrendArgs_Req_DEFAULT *core_api.DashboardGetDataTrendReq

func (p *DashboardGetDataTrendArgs) GetReq() *core_api.DashboardGetDataTrendReq {
	if !p.IsSetReq() {
		return DashboardGetDataTrendArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetDataTrendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetDataTrendArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetDataTrendResult struct {
	Success *core_api.DashboardGetDataTrendResp
}

var DashboardGetDataTrendResult_Success_DEFAULT *core_api.DashboardGetDataTrendResp

func (p *DashboardGetDataTrendResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetDataTrendResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetDataTrendResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetDataTrendResult) GetSuccess() *core_api.DashboardGetDataTrendResp {
	if !p.IsSetSuccess() {
		return DashboardGetDataTrendResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetDataTrendResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetDataTrendResp)
}

func (p *DashboardGetDataTrendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetDataTrendResult) GetResult() interface{} {
	return p.Success
}

func dashboardListUnitsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListUnitsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).DashboardListUnits(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListUnitsArgs:
		success, err := handler.(core_api.CoreApi).DashboardListUnits(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListUnitsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListUnitsArgs() interface{} {
	return &DashboardListUnitsArgs{}
}

func newDashboardListUnitsResult() interface{} {
	return &DashboardListUnitsResult{}
}

type DashboardListUnitsArgs struct {
	Req *core_api.DashboardListUnitsReq
}

func (p *DashboardListUnitsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListUnitsArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUnitsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListUnitsArgs_Req_DEFAULT *core_api.DashboardListUnitsReq

func (p *DashboardListUnitsArgs) GetReq() *core_api.DashboardListUnitsReq {
	if !p.IsSetReq() {
		return DashboardListUnitsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListUnitsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListUnitsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListUnitsResult struct {
	Success *core_api.DashboardListUnitsResp
}

var DashboardListUnitsResult_Success_DEFAULT *core_api.DashboardListUnitsResp

func (p *DashboardListUnitsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListUnitsResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUnitsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListUnitsResult) GetSuccess() *core_api.DashboardListUnitsResp {
	if !p.IsSetSuccess() {
		return DashboardListUnitsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListUnitsResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListUnitsResp)
}

func (p *DashboardListUnitsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListUnitsResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetPsychTrendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetPsychTrendReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).DashboardGetPsychTrend(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetPsychTrendArgs:
		success, err := handler.(core_api.CoreApi).DashboardGetPsychTrend(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetPsychTrendResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetPsychTrendArgs() interface{} {
	return &DashboardGetPsychTrendArgs{}
}

func newDashboardGetPsychTrendResult() interface{} {
	return &DashboardGetPsychTrendResult{}
}

type DashboardGetPsychTrendArgs struct {
	Req *core_api.DashboardGetPsychTrendReq
}

func (p *DashboardGetPsychTrendArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetPsychTrendArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetPsychTrendReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetPsychTrendArgs_Req_DEFAULT *core_api.DashboardGetPsychTrendReq

func (p *DashboardGetPsychTrendArgs) GetReq() *core_api.DashboardGetPsychTrendReq {
	if !p.IsSetReq() {
		return DashboardGetPsychTrendArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetPsychTrendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetPsychTrendArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetPsychTrendResult struct {
	Success *core_api.DashboardGetPsychTrendResp
}

var DashboardGetPsychTrendResult_Success_DEFAULT *core_api.DashboardGetPsychTrendResp

func (p *DashboardGetPsychTrendResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetPsychTrendResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetPsychTrendResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetPsychTrendResult) GetSuccess() *core_api.DashboardGetPsychTrendResp {
	if !p.IsSetSuccess() {
		return DashboardGetPsychTrendResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetPsychTrendResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetPsychTrendResp)
}

func (p *DashboardGetPsychTrendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetPsychTrendResult) GetResult() interface{} {
	return p.Success
}

func dashboardGetAlarmOverviewHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardGetAlarmOverviewReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).DashboardGetAlarmOverview(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardGetAlarmOverviewArgs:
		success, err := handler.(core_api.CoreApi).DashboardGetAlarmOverview(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardGetAlarmOverviewResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardGetAlarmOverviewArgs() interface{} {
	return &DashboardGetAlarmOverviewArgs{}
}

func newDashboardGetAlarmOverviewResult() interface{} {
	return &DashboardGetAlarmOverviewResult{}
}

type DashboardGetAlarmOverviewArgs struct {
	Req *core_api.DashboardGetAlarmOverviewReq
}

func (p *DashboardGetAlarmOverviewArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardGetAlarmOverviewArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetAlarmOverviewReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardGetAlarmOverviewArgs_Req_DEFAULT *core_api.DashboardGetAlarmOverviewReq

func (p *DashboardGetAlarmOverviewArgs) GetReq() *core_api.DashboardGetAlarmOverviewReq {
	if !p.IsSetReq() {
		return DashboardGetAlarmOverviewArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardGetAlarmOverviewArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardGetAlarmOverviewArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardGetAlarmOverviewResult struct {
	Success *core_api.DashboardGetAlarmOverviewResp
}

var DashboardGetAlarmOverviewResult_Success_DEFAULT *core_api.DashboardGetAlarmOverviewResp

func (p *DashboardGetAlarmOverviewResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardGetAlarmOverviewResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardGetAlarmOverviewResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardGetAlarmOverviewResult) GetSuccess() *core_api.DashboardGetAlarmOverviewResp {
	if !p.IsSetSuccess() {
		return DashboardGetAlarmOverviewResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardGetAlarmOverviewResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardGetAlarmOverviewResp)
}

func (p *DashboardGetAlarmOverviewResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardGetAlarmOverviewResult) GetResult() interface{} {
	return p.Success
}

func dashboardListAlarmRecordsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListAlarmRecordsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).DashboardListAlarmRecords(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListAlarmRecordsArgs:
		success, err := handler.(core_api.CoreApi).DashboardListAlarmRecords(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListAlarmRecordsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListAlarmRecordsArgs() interface{} {
	return &DashboardListAlarmRecordsArgs{}
}

func newDashboardListAlarmRecordsResult() interface{} {
	return &DashboardListAlarmRecordsResult{}
}

type DashboardListAlarmRecordsArgs struct {
	Req *core_api.DashboardListAlarmRecordsReq
}

func (p *DashboardListAlarmRecordsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListAlarmRecordsArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListAlarmRecordsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListAlarmRecordsArgs_Req_DEFAULT *core_api.DashboardListAlarmRecordsReq

func (p *DashboardListAlarmRecordsArgs) GetReq() *core_api.DashboardListAlarmRecordsReq {
	if !p.IsSetReq() {
		return DashboardListAlarmRecordsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListAlarmRecordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListAlarmRecordsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListAlarmRecordsResult struct {
	Success *core_api.DashboardListAlarmRecordsResp
}

var DashboardListAlarmRecordsResult_Success_DEFAULT *core_api.DashboardListAlarmRecordsResp

func (p *DashboardListAlarmRecordsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListAlarmRecordsResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListAlarmRecordsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListAlarmRecordsResult) GetSuccess() *core_api.DashboardListAlarmRecordsResp {
	if !p.IsSetSuccess() {
		return DashboardListAlarmRecordsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListAlarmRecordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListAlarmRecordsResp)
}

func (p *DashboardListAlarmRecordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListAlarmRecordsResult) GetResult() interface{} {
	return p.Success
}

func dashboardListClassesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListClassesReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).DashboardListClasses(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListClassesArgs:
		success, err := handler.(core_api.CoreApi).DashboardListClasses(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListClassesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListClassesArgs() interface{} {
	return &DashboardListClassesArgs{}
}

func newDashboardListClassesResult() interface{} {
	return &DashboardListClassesResult{}
}

type DashboardListClassesArgs struct {
	Req *core_api.DashboardListClassesReq
}

func (p *DashboardListClassesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListClassesArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListClassesReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListClassesArgs_Req_DEFAULT *core_api.DashboardListClassesReq

func (p *DashboardListClassesArgs) GetReq() *core_api.DashboardListClassesReq {
	if !p.IsSetReq() {
		return DashboardListClassesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListClassesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListClassesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListClassesResult struct {
	Success *core_api.DashboardListClassesResp
}

var DashboardListClassesResult_Success_DEFAULT *core_api.DashboardListClassesResp

func (p *DashboardListClassesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListClassesResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListClassesResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListClassesResult) GetSuccess() *core_api.DashboardListClassesResp {
	if !p.IsSetSuccess() {
		return DashboardListClassesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListClassesResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListClassesResp)
}

func (p *DashboardListClassesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListClassesResult) GetResult() interface{} {
	return p.Success
}

func dashboardListUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(core_api.DashboardListUsersReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(core_api.CoreApi).DashboardListUsers(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DashboardListUsersArgs:
		success, err := handler.(core_api.CoreApi).DashboardListUsers(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DashboardListUsersResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDashboardListUsersArgs() interface{} {
	return &DashboardListUsersArgs{}
}

func newDashboardListUsersResult() interface{} {
	return &DashboardListUsersResult{}
}

type DashboardListUsersArgs struct {
	Req *core_api.DashboardListUsersReq
}

func (p *DashboardListUsersArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DashboardListUsersArgs) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUsersReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DashboardListUsersArgs_Req_DEFAULT *core_api.DashboardListUsersReq

func (p *DashboardListUsersArgs) GetReq() *core_api.DashboardListUsersReq {
	if !p.IsSetReq() {
		return DashboardListUsersArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DashboardListUsersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DashboardListUsersArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DashboardListUsersResult struct {
	Success *core_api.DashboardListUsersResp
}

var DashboardListUsersResult_Success_DEFAULT *core_api.DashboardListUsersResp

func (p *DashboardListUsersResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DashboardListUsersResult) Unmarshal(in []byte) error {
	msg := new(core_api.DashboardListUsersResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DashboardListUsersResult) GetSuccess() *core_api.DashboardListUsersResp {
	if !p.IsSetSuccess() {
		return DashboardListUsersResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DashboardListUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*core_api.DashboardListUsersResp)
}

func (p *DashboardListUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DashboardListUsersResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UserSignUp(ctx context.Context, Req *core_api.UserSignUpReq) (r *core_api.UserSignUpResp, err error) {
	var _args UserSignUpArgs
	_args.Req = Req
	var _result UserSignUpResult
	if err = p.c.Call(ctx, "UserSignUp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserSignIn(ctx context.Context, Req *core_api.UserSignInReq) (r *core_api.UserSignInResp, err error) {
	var _args UserSignInArgs
	_args.Req = Req
	var _result UserSignInResult
	if err = p.c.Call(ctx, "UserSignIn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserGetInfo(ctx context.Context, Req *core_api.UserGetInfoReq) (r *core_api.UserGetInfoResp, err error) {
	var _args UserGetInfoArgs
	_args.Req = Req
	var _result UserGetInfoResult
	if err = p.c.Call(ctx, "UserGetInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserUpdateInfo(ctx context.Context, Req *core_api.UserUpdateInfoReq) (r *basic.Response, err error) {
	var _args UserUpdateInfoArgs
	_args.Req = Req
	var _result UserUpdateInfoResult
	if err = p.c.Call(ctx, "UserUpdateInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserUpdatePassword(ctx context.Context, Req *core_api.UserUpdatePasswordReq) (r *basic.Response, err error) {
	var _args UserUpdatePasswordArgs
	_args.Req = Req
	var _result UserUpdatePasswordResult
	if err = p.c.Call(ctx, "UserUpdatePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitSignUp(ctx context.Context, Req *core_api.UnitSignUpReq) (r *core_api.UnitSignUpResp, err error) {
	var _args UnitSignUpArgs
	_args.Req = Req
	var _result UnitSignUpResult
	if err = p.c.Call(ctx, "UnitSignUp", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitSignIn(ctx context.Context, Req *core_api.UnitSignInReq) (r *core_api.UnitSignInResp, err error) {
	var _args UnitSignInArgs
	_args.Req = Req
	var _result UnitSignInResult
	if err = p.c.Call(ctx, "UnitSignIn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitGetInfo(ctx context.Context, Req *core_api.UnitGetInfoReq) (r *core_api.UnitGetInfoResp, err error) {
	var _args UnitGetInfoArgs
	_args.Req = Req
	var _result UnitGetInfoResult
	if err = p.c.Call(ctx, "UnitGetInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitUpdateInfo(ctx context.Context, Req *core_api.UnitUpdateInfoReq) (r *basic.Response, err error) {
	var _args UnitUpdateInfoArgs
	_args.Req = Req
	var _result UnitUpdateInfoResult
	if err = p.c.Call(ctx, "UnitUpdateInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitUpdatePassword(ctx context.Context, Req *core_api.UnitUpdatePasswordReq) (r *basic.Response, err error) {
	var _args UnitUpdatePasswordArgs
	_args.Req = Req
	var _result UnitUpdatePasswordResult
	if err = p.c.Call(ctx, "UnitUpdatePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitLinkUser(ctx context.Context, Req *core_api.UnitLinkUserReq) (r *basic.Response, err error) {
	var _args UnitLinkUserArgs
	_args.Req = Req
	var _result UnitLinkUserResult
	if err = p.c.Call(ctx, "UnitLinkUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnitCreateAndLinkUser(ctx context.Context, Req *core_api.UnitCreateAndLinkUserReq) (r *core_api.UnitCreateAndLinkUserResp, err error) {
	var _args UnitCreateAndLinkUserArgs
	_args.Req = Req
	var _result UnitCreateAndLinkUserResult
	if err = p.c.Call(ctx, "UnitCreateAndLinkUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigCreate(ctx context.Context, Req *core_api.ConfigCreateOrUpdateReq) (r *basic.Response, err error) {
	var _args ConfigCreateArgs
	_args.Req = Req
	var _result ConfigCreateResult
	if err = p.c.Call(ctx, "ConfigCreate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigUpdateInfo(ctx context.Context, Req *core_api.ConfigCreateOrUpdateReq) (r *basic.Response, err error) {
	var _args ConfigUpdateInfoArgs
	_args.Req = Req
	var _result ConfigUpdateInfoResult
	if err = p.c.Call(ctx, "ConfigUpdateInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigGetByUnitID(ctx context.Context, Req *core_api.ConfigGetByUnitIdReq) (r *core_api.ConfigGetByUnitIdResp, err error) {
	var _args ConfigGetByUnitIDArgs
	_args.Req = Req
	var _result ConfigGetByUnitIDResult
	if err = p.c.Call(ctx, "ConfigGetByUnitID", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetDataOverview(ctx context.Context, Req *core_api.DashboardGetDataOverviewReq) (r *core_api.DashboardGetDataOverviewResp, err error) {
	var _args DashboardGetDataOverviewArgs
	_args.Req = Req
	var _result DashboardGetDataOverviewResult
	if err = p.c.Call(ctx, "DashboardGetDataOverview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetDataTrend(ctx context.Context, Req *core_api.DashboardGetDataTrendReq) (r *core_api.DashboardGetDataTrendResp, err error) {
	var _args DashboardGetDataTrendArgs
	_args.Req = Req
	var _result DashboardGetDataTrendResult
	if err = p.c.Call(ctx, "DashboardGetDataTrend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListUnits(ctx context.Context, Req *core_api.DashboardListUnitsReq) (r *core_api.DashboardListUnitsResp, err error) {
	var _args DashboardListUnitsArgs
	_args.Req = Req
	var _result DashboardListUnitsResult
	if err = p.c.Call(ctx, "DashboardListUnits", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetPsychTrend(ctx context.Context, Req *core_api.DashboardGetPsychTrendReq) (r *core_api.DashboardGetPsychTrendResp, err error) {
	var _args DashboardGetPsychTrendArgs
	_args.Req = Req
	var _result DashboardGetPsychTrendResult
	if err = p.c.Call(ctx, "DashboardGetPsychTrend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardGetAlarmOverview(ctx context.Context, Req *core_api.DashboardGetAlarmOverviewReq) (r *core_api.DashboardGetAlarmOverviewResp, err error) {
	var _args DashboardGetAlarmOverviewArgs
	_args.Req = Req
	var _result DashboardGetAlarmOverviewResult
	if err = p.c.Call(ctx, "DashboardGetAlarmOverview", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListAlarmRecords(ctx context.Context, Req *core_api.DashboardListAlarmRecordsReq) (r *core_api.DashboardListAlarmRecordsResp, err error) {
	var _args DashboardListAlarmRecordsArgs
	_args.Req = Req
	var _result DashboardListAlarmRecordsResult
	if err = p.c.Call(ctx, "DashboardListAlarmRecords", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListClasses(ctx context.Context, Req *core_api.DashboardListClassesReq) (r *core_api.DashboardListClassesResp, err error) {
	var _args DashboardListClassesArgs
	_args.Req = Req
	var _result DashboardListClassesResult
	if err = p.c.Call(ctx, "DashboardListClasses", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DashboardListUsers(ctx context.Context, Req *core_api.DashboardListUsersReq) (r *core_api.DashboardListUsersResp, err error) {
	var _args DashboardListUsersArgs
	_args.Req = Req
	var _result DashboardListUsersResult
	if err = p.c.Call(ctx, "DashboardListUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
