syntax = "proto3";

package core_api;

option go_package = "./core_api";

import "basic/pagination.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/any.proto";
import "basic/http.proto";

// 聊天应用配置
message ChatApp {
  string name = 1;
  string description = 2;
  string provider = 3;
  string appId = 4;
};

// TTS应用配置
message TTSApp {
  string name = 1;
  string description = 2;
  string provider = 3;
  string appId = 4;
  string speaker = 5;
};

// 报表应用配置
message ReportApp {
  string name = 1;
  string description = 2;
  string provider = 3;
  string appId = 4;
}

// 心理老师虚拟形象
message Character {
  // 角色ID
  string id = 1;
  // 教师名称
  string name = 2;
  // 音色配置
  string voice = 3;
  // 形象图片url
  string image = 4;
  // 是否删除
  int32 status = 5;
  // 背景人设
  string identity = 6;
  // 模型对话风格
  string style = 7;
  // 开场白
  string greeting = 8;
}

// 单位全量配置（包含对话bot、TTS、报表、角色、对话场景、告警手机号等）
message ConfigVO {
  string unitId = 1;
  // 对话engine实现模式 1-2: Chain | End2End
  int32 type = 2;
  ChatApp chat = 3;
  TTSApp tts = 4;
  ReportApp report = 5;
  // 1-2: Active | Deleted
  int32 status = 6;
  int64 createTime = 7;
  int64 updateTime = 8;
  string modelView = 9;
  string backgroundImage = 10;
  // 心理老师角色列表
  repeated Character characters = 11;
  // 对话背景图列表
  repeated string scene = 12;
  // 接收告警短信的手机号列表
  repeated string alertPhone = 13;
}

// 创建或更新配置请求（超管可配置全量；单位管理员/教师仅可配置角色/场景/告警手机号）
message ConfigCreateOrUpdateReq {
  ConfigVO config = 1;
}

// 获取单位配置请求（超管返回全量；单位管理员/教师返回角色/场景/告警手机号等）
message ConfigGetByUnitIdReq {
  string unitId = 1;
}
// 获取单位全量配置响应
message ConfigGetByUnitIdResp {
  ConfigVO config = 1;
  int32 code = 255;
  string msg = 256;
}

// 获取单位所有角色请求（无需鉴权，可用于学生端获取对话角色列表）
message ConfigGetCharacterReq {
  string unitId = 1;
}
// 获取心理老师角色列表及对话背景（无需鉴权，返回该单位所有character及对话场景，可用于学生端展示）
message ConfigGetCharacterResp {
  // 心理老师角色列表
  repeated Character characters = 1;
  // 对话背景图/场景列表
  repeated string scene = 2;
  int32 code = 255;
  string msg = 256;
}

// 音色信息
message VoiceItemVO {
  string id = 1;
  string voiceType = 2;
  string name = 3;
  string avatar = 4;
  string gender = 5;
  string age = 6;
  string description = 7;
  string trialUrl = 8;
  string volcanoId = 9;
  string resourceId = 10;
  int64 createTime = 11;
  int64 updateTime = 12;
}

// 获取音色列表请求
message ConfigListVoiceReq {
  basic.PaginationOptions paginationOptions = 1;
}

// 获取音色列表响应
message ConfigListVoiceResp {
  repeated VoiceItemVO voices = 1;
  basic.Pagination pagination = 2;
  int32 code = 255;
  string msg = 256;
}

// 向单位新增角色请求
message ConfigAddCharacterReq {
  // 单位ID
  string unitId = 1;
  // 角色信息
  Character character = 2;
}

// 向单位新增角色响应
message ConfigAddCharacterResp {
  int32 code = 255;
  string msg = 256;
}
