syntax = "proto3";

package core_api;

option go_package = "./core_api";

import "google/api/annotations.proto";
import "core_api/user.proto";
import "core_api/unit.proto";
import "core_api/config.proto";
import "core_api/dashboard.proto";
import "core_api/conversation.proto";
import "basic/re.proto";

service User {
  rpc UserSignIn(UserSignInReq) returns (UserSignInResp){
            option (google.api.http) = {
      post: "/user/sign_in"
      body: "*"
    };
  }
  rpc UserGetInfo(UserGetInfoReq) returns (UserGetInfoResp){
            option (google.api.http) = {
      get: "/user/get_info"
    };
  }
  rpc UserUpdateInfo(UserUpdateInfoReq) returns (basic.Response){
            option (google.api.http) = {
      post: "/user/update_info"
      body: "*"
    };
  }
  rpc UserUpdatePassword(UserUpdatePasswordReq) returns (basic.Response){
            option (google.api.http) = {
      post: "/user/update_password"
      body: "*"
    };
  }
  rpc CreateUser(CreateUserReq) returns (CreateUserResp){
            option (google.api.http) = {
      post: "/user/create"
      body: "*"
    };
  }
  rpc SendVerifyCode(SendVerifyCodeReq) returns (basic.Response){
            option (google.api.http) = {
      post: "/user/send_verify_code"
      body: "*"
    };
  }
}

service Unit {
  rpc UnitGetInfo(UnitGetInfoReq) returns (UnitGetInfoResp){
            option (google.api.http) = {
      get: "/unit/get_info"
    };
  }
  rpc UnitUpdateInfo(UnitUpdateInfoReq) returns (basic.Response){
            option (google.api.http) = {
      post: "/unit/update_info"
      body: "*"
    };
  }
  rpc UnitGetByURI(UnitGetByURIReq) returns (UnitGetByURIResp) {
            option (google.api.http) = {
      post: "/unit/get_by_uri"
      body: "*"
    };
  }
  rpc CreateUnit(CreateUnitReq) returns (basic.Response) {
            option (google.api.http) = {
      post: "/unit/create"
      body: "*"
    };
  }
}

service Config {
  // 创建单位配置
  rpc ConfigCreate(ConfigCreateOrUpdateReq) returns (basic.Response){
            option (google.api.http) = {
      post: "/config/create"
      body: "*"
    };
  }
  // 更新单位配置（可用于更新/配置单位对话bot、告警手机号、对话场景等）
  rpc ConfigUpdateInfo(ConfigCreateOrUpdateReq) returns (basic.Response){
            option (google.api.http) = {
      post: "/config/update_info"
      body: "*"
    };
  }
  // 获取单位全量配置
  rpc ConfigGetByUnitID(ConfigGetByUnitIdReq) returns (ConfigGetByUnitIdResp){
            option (google.api.http) = {
      get: "/config/get_by_unit_id"
    };
  }
  // 获取单位所有角色（无需鉴权，可用于学生端）
  rpc ConfigGetCharacter(ConfigGetCharacterReq) returns (ConfigGetCharacterResp){
            option (google.api.http) = {
      get: "/config/get_character"
    };
  }
  // 获取音色列表
  rpc ConfigListVoice(ConfigListVoiceReq) returns (ConfigListVoiceResp){
            option (google.api.http) = {
      get: "/config/list_voice"
    };
  }
  // 向单位新增心理老师角色
  rpc ConfigAddCharacter(ConfigAddCharacterReq) returns (ConfigAddCharacterResp){
            option (google.api.http) = {
      post: "/config/add_character"
      body: "*"
    };
  }
  // 更新单位心理老师角色
  rpc ConfigUpdateCharacter(ConfigUpdateCharacterReq) returns (ConfigUpdateCharacterResp){
            option (google.api.http) = {
      post: "/config/update_character"
      body: "*"
    };
  }
  // 删除单位心理老师角色（软删除）
  rpc ConfigDeleteCharacter(ConfigDeleteCharacterReq) returns (ConfigDeleteCharacterResp){
            option (google.api.http) = {
      post: "/config/delete_character"
      body: "*"
    };
  }
}

service Dashboard {
  rpc DashboardGetDataOverview(DashboardGetDataOverviewReq) returns (DashboardGetDataOverviewResp) {
            option (google.api.http) = {
      post: "/dashboard/overview"
      body: "*"
    };
  }
  rpc DashboardGetDataTrend(DashboardGetDataTrendReq) returns (DashboardGetDataTrendResp) {
            option (google.api.http) = {
      post: "/dashboard/trend"
      body: "*"
    };
  }
  rpc DashboardListUnits(DashboardListUnitsReq) returns (DashboardListUnitsResp) {
            option (google.api.http) = {
      post: "/dashboard/units"
      body: "*"
    };
  }
  rpc DashboardGetPsychTrend(DashboardGetPsychTrendReq) returns (DashboardGetPsychTrendResp) {
            option (google.api.http) = {
      post: "/dashboard/psych_trend"
      body: "*"
    };
  }
  rpc DashboardGetAlarmOverview(DashboardGetAlarmOverviewReq) returns (DashboardGetAlarmOverviewResp) {
            option (google.api.http) = {
      post: "/dashboard/alarm_overview"
      body: "*"
    };
  }
  rpc DashboardListAlarmRecords(DashboardListAlarmRecordsReq) returns (DashboardListAlarmRecordsResp) {
            option (google.api.http) = {
      post: "/dashboard/alarm_records"
      body: "*"
    };
  }
  rpc DashboardUpdateAlarm(DashboardUpdateAlarmReq) returns (DashboardUpdateAlarmResp) {
            option (google.api.http) = {
      post: "/dashboard/update_alarm"
      body: "*"
    };
  }
  rpc DashboardListClasses(DashboardListClassesReq) returns (DashboardListClassesResp) {
            option (google.api.http) = {
      post: "/dashboard/classes"
      body: "*"
    };
  }
  rpc DashboardListUsers(DashboardListUsersReq) returns (DashboardListUsersResp) {
            option (google.api.http) = {
      post: "/dashboard/users"
      body: "*"
    };
  }
  rpc DashboardUserConvRecords(DashboardUserConvRecordsReq) returns (DashboardUserConvRecordsResp) {
            option (google.api.http) = {
      post: "/dashboard/user_conversation_records"
      body: "*"
    };
  }
  rpc DashboardUnitConvRecords(DashboardUnitConvRecordsReq) returns (DashboardUnitConvRecordsResp) {
            option (google.api.http) = {
      post: "/dashboard/unit_conversation_records"
      body: "*"
    };
  }
  rpc DashboardGetReport(DashboardGetReportReq) returns (DashboardGetReportResp) {
            option (google.api.http) = {
      post: "/dashboard/get_report"
      body: "*"
    };
  }
  rpc DashboardCreateRemark(DashboardCreateRemarkReq) returns (DashboardCreateRemarkResp) {
            option (google.api.http) = {
      post: "/dashboard/create_remark"
      body: "*"
    };
  }
}

service Conversation {
  rpc CreateConversation (CreateConversationReq) returns (CreateConversationResp) {
            option (google.api.http) = {
      post: "/conversation/create"
      body: "*"
    };
  }
  rpc ListConversations (ListConversationsReq) returns (ListConversationsResp) {
            option (google.api.http) = {
      post: "/conversation/list"
      body: "*"
    };
  }
  rpc GetSingleConv (GetSingleConvReq) returns (GetSingleConvResp) {
            option (google.api.http) = {
      post: "/conversation/get_single"
      body: "*"
    };
  }
  rpc GetConvByDate (GetConvByDateReq) returns (GetConvByDateResp) {
            option (google.api.http) = {
      post: "/conversation/get_by_date"
      body: "*"
    };
  }
}